<?xml version="1.0" encoding="utf-8"?>
<!-- Created by Leo: http://leoeditor.com/leo_toc.html -->
<leo_file xmlns:leo="http://leoeditor.com/namespaces/leo-python-editor/1.1" >
<leo_header file_format="2"/>
<globals/>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="leo.20190426102417.1"><vh>@settings</vh>
<v t="leo.20190426102417.2"><vh>@data qt-gui-plugin-style-sheet</vh></v>
<v t="leo.20190426102417.3"><vh>@string initial_split_orientation = horizontal</vh></v>
</v>
<v t="leo.20190426102408.2"><vh>@clean index.html</vh>
<v t="leo.20190426102506.1"><vh>&lt;html lang="en"&gt; (index.html)</vh>
<v t="leo.20190426102506.2"><vh>&lt;head&gt; (index.html)</vh>
<v t="leo.20190426102506.3"><vh>&lt;title&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.4"><vh>&lt;body&gt; (index.html)</vh>
<v t="leo.20190426102506.5"><vh>&lt;div class="container"&gt; (index.html)</vh>
<v t="leo.20190426102506.6"><vh>&lt;div class="navbar-header"&gt; (index.html)</vh>
<v t="leo.20190426102506.7"><vh>&lt;button aria-controls="main-navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#main-navbar" data-toggle="collapse" type="button"&gt; (index.html)</vh>
<v t="leo.20190426102506.8"><vh>&lt;span class="navbar-toggler-icon"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.9"><vh>&lt;span class="icon-menu"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.10"><vh>&lt;span class="icon-menu"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.11"><vh>&lt;span class="icon-menu"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.12"><vh>&lt;a class="navbar-brand" href="index.html"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.13"><vh>&lt;div class="collapse navbar-collapse" id="main-navbar"&gt; (index.html)</vh>
<v t="leo.20190426102506.14"><vh>&lt;ul class="navbar-nav mr-auto w-100 justify-content-end clearfix"&gt; (index.html)</vh>
<v t="leo.20190426102506.15"><vh>&lt;li class="nav-item active"&gt; (index.html)</vh>
<v t="leo.20190426102506.16"><vh>&lt;a class="nav-link" href="#sliders"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.17"><vh>&lt;li class="nav-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.18"><vh>&lt;a class="nav-link" href="#about"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.19"><vh>&lt;li class="nav-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.20"><vh>&lt;a class="nav-link" href="#services"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.21"><vh>&lt;li class="nav-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.22"><vh>&lt;a class="nav-link" href="#portfolio"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.23"><vh>&lt;li class="nav-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.24"><vh>&lt;a class="nav-link" href="#feature"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.25"><vh>&lt;li class="nav-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.26"><vh>&lt;a class="nav-link" href="#team"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.27"><vh>&lt;li class="nav-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.28"><vh>&lt;a class="nav-link" href="#pricing"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.29"><vh>&lt;li class="nav-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.30"><vh>&lt;a class="nav-link" href="#contact"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.31"><vh>&lt;ul class="mobile-menu navbar-nav"&gt; (index.html)</vh>
<v t="leo.20190426102506.32"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.33"><vh>&lt;a class="page-scroll" href="#sliders"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.34"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.35"><vh>&lt;a class="page-scroll" href="#about"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.36"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.37"><vh>&lt;a class="page-scroll" href="#services"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.38"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.39"><vh>&lt;a class="page-scroll" href="#portfolio"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.40"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.41"><vh>&lt;a class="page-scroll" href="#feature"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.42"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.43"><vh>&lt;a class="page-scroll" href="#team"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.44"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.45"><vh>&lt;a class="page-scroll" href="#pricing"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.46"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.47"><vh>&lt;a class="page-scroll" href="#contact"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.48"><vh>&lt;div id="sliders"&gt; (index.html)</vh>
<v t="leo.20190426102506.49"><vh>&lt;div class="full-width"&gt; (index.html)</vh>
<v t="leo.20190426102506.50"><vh>&lt;div class="carousel slide" id="light-slider"&gt; (index.html)</vh>
<v t="leo.20190426102506.51"><vh>&lt;div id="carousel-area"&gt; (index.html)</vh>
<v t="leo.20190426102506.52"><vh>&lt;div class="carousel slide" data-ride="carousel" id="carousel-slider"&gt; (index.html)</vh>
<v t="leo.20190426102506.53"><vh>&lt;ol class="carousel-indicators"&gt; (index.html)</vh>
<v t="leo.20190426102506.54"><vh>&lt;li class="active" data-slide-to="0" data-target="#carousel-slider"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.55"><vh>&lt;li data-slide-to="1" data-target="#carousel-slider"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.56"><vh>&lt;li data-slide-to="2" data-target="#carousel-slider"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.57"><vh>&lt;div class="carousel-inner" role="listbox"&gt; (index.html)</vh>
<v t="leo.20190426102506.58"><vh>&lt;div class="carousel-item active"&gt; (index.html)</vh>
<v t="leo.20190426102506.59"><vh>&lt;div class="carousel-caption"&gt; (index.html)</vh>
<v t="leo.20190426102506.60"><vh>&lt;h3 class="slide-title animated fadeInDown"&gt; (index.html)</vh>
<v t="leo.20190426102506.61"><vh>&lt;span&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.62"><vh>&lt;h5 class="slide-text animated fadeIn"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.63"><vh>&lt;a class="btn btn-lg btn-common animated fadeInUp" href="#"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.64"><vh>&lt;a class="btn btn-lg btn-border animated fadeInUp" href="#"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.65"><vh>&lt;div class="carousel-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.66"><vh>&lt;div class="carousel-caption"&gt; (index.html)</vh>
<v t="leo.20190426102506.67"><vh>&lt;h3 class="slide-title animated fadeInDown"&gt; (index.html)</vh>
<v t="leo.20190426102506.68"><vh>&lt;span&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.69"><vh>&lt;h5 class="slide-text animated fadeIn"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.70"><vh>&lt;a class="btn btn-lg btn-common animated fadeInUp" href="#"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.71"><vh>&lt;div class="carousel-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.72"><vh>&lt;div class="carousel-caption"&gt; (index.html)</vh>
<v t="leo.20190426102506.73"><vh>&lt;h3 class="slide-title animated fadeInDown"&gt; (index.html)</vh>
<v t="leo.20190426102506.74"><vh>&lt;span&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.75"><vh>&lt;h5 class="slide-text animated fadeIn"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.76"><vh>&lt;a class="btn btn-lg btn-border animated fadeInUp" href="#"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.77"><vh>&lt;a class="btn btn-lg btn-common animated fadeInUp" href="#"&gt; (index.html)</vh></v>
</v>
</v>
</v>
<v t="leo.20190426102506.78"><vh>&lt;a class="carousel-control-prev" data-slide="prev" href="#carousel-slider" role="button"&gt; (index.html)</vh>
<v t="leo.20190426102506.79"><vh>&lt;i class="fa fa-chevron-left"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.80"><vh>&lt;a class="carousel-control-next" data-slide="next" href="#carousel-slider" role="button"&gt; (index.html)</vh>
<v t="leo.20190426102506.81"><vh>&lt;i class="fa fa-chevron-right"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.82"><vh>&lt;div class="section-padding" id="about"&gt; (index.html)</vh>
<v t="leo.20190426102506.83"><vh>&lt;div class="container"&gt; (index.html)</vh>
<v t="leo.20190426102506.84"><vh>&lt;div class="row"&gt; (index.html)</vh>
<v t="leo.20190426102506.85"><vh>&lt;div class="col-lg-3 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.86"><vh>&lt;div class="about block text-center"&gt; (index.html)</vh>
<v t="leo.20190426102506.87"><vh>&lt;h5&gt; (index.html)</vh>
<v t="leo.20190426102506.88"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.89"><vh>&lt;p&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.90"><vh>&lt;div class="col-lg-3 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.91"><vh>&lt;div class="about block text-center"&gt; (index.html)</vh>
<v t="leo.20190426102506.92"><vh>&lt;h5&gt; (index.html)</vh>
<v t="leo.20190426102506.93"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.94"><vh>&lt;p&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.95"><vh>&lt;div class="col-lg-3 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.96"><vh>&lt;div class="about block text-center"&gt; (index.html)</vh>
<v t="leo.20190426102506.97"><vh>&lt;h5&gt; (index.html)</vh>
<v t="leo.20190426102506.98"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.99"><vh>&lt;p&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.100"><vh>&lt;div class="col-lg-3 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.101"><vh>&lt;div class="about block text-center"&gt; (index.html)</vh>
<v t="leo.20190426102506.102"><vh>&lt;h5&gt; (index.html)</vh>
<v t="leo.20190426102506.103"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.104"><vh>&lt;p&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.105"><vh>&lt;div class="container"&gt; (index.html)</vh>
<v t="leo.20190426102506.106"><vh>&lt;div class="row"&gt; (index.html)</vh>
<v t="leo.20190426102506.107"><vh>&lt;div class="col-md-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.108"><vh>&lt;h2 class="section-title wow fadeInDown animated" data-wow-delay="0.3s"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.109"><vh>&lt;div class="row"&gt; (index.html)</vh>
<v t="leo.20190426102506.110"><vh>&lt;div class="col-md-6 col-lg-4 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.111"><vh>&lt;div class="service-box"&gt; (index.html)</vh>
<v t="leo.20190426102506.112"><vh>&lt;div class="service-icon"&gt; (index.html)</vh>
<v t="leo.20190426102506.113"><vh>&lt;i class="fa fa-cogs"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.114"><vh>&lt;div class="service-content"&gt; (index.html)</vh>
<v t="leo.20190426102506.115"><vh>&lt;h4&gt; (index.html)</vh>
<v t="leo.20190426102506.116"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.117"><vh>&lt;p&gt; (index.html)</vh></v>
</v>
</v>
</v>
<v t="leo.20190426102506.118"><vh>&lt;div class="col-md-6 col-lg-4 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.119"><vh>&lt;div class="service-box"&gt; (index.html)</vh>
<v t="leo.20190426102506.120"><vh>&lt;div class="service-icon"&gt; (index.html)</vh>
<v t="leo.20190426102506.121"><vh>&lt;i class="fa fa-cubes"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.122"><vh>&lt;div class="service-content"&gt; (index.html)</vh>
<v t="leo.20190426102506.123"><vh>&lt;h4&gt; (index.html)</vh>
<v t="leo.20190426102506.124"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.125"><vh>&lt;p&gt; (index.html)</vh></v>
</v>
</v>
</v>
<v t="leo.20190426102506.126"><vh>&lt;div class="col-md-6 col-lg-4 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.127"><vh>&lt;div class="service-box"&gt; (index.html)</vh>
<v t="leo.20190426102506.128"><vh>&lt;div class="service-icon"&gt; (index.html)</vh>
<v t="leo.20190426102506.129"><vh>&lt;i class="fa fa-tachometer"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.130"><vh>&lt;div class="service-content"&gt; (index.html)</vh>
<v t="leo.20190426102506.131"><vh>&lt;h4&gt; (index.html)</vh>
<v t="leo.20190426102506.132"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.133"><vh>&lt;p&gt; (index.html)</vh></v>
</v>
</v>
</v>
<v t="leo.20190426102506.134"><vh>&lt;div class="col-md-6 col-lg-4 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.135"><vh>&lt;div class="service-box"&gt; (index.html)</vh>
<v t="leo.20190426102506.136"><vh>&lt;div class="service-icon"&gt; (index.html)</vh>
<v t="leo.20190426102506.137"><vh>&lt;i class="fa fa-check"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.138"><vh>&lt;div class="service-content"&gt; (index.html)</vh>
<v t="leo.20190426102506.139"><vh>&lt;h4&gt; (index.html)</vh>
<v t="leo.20190426102506.140"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.141"><vh>&lt;p&gt; (index.html)</vh></v>
</v>
</v>
</v>
<v t="leo.20190426102506.142"><vh>&lt;div class="col-md-6 col-lg-4 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.143"><vh>&lt;div class="service-box"&gt; (index.html)</vh>
<v t="leo.20190426102506.144"><vh>&lt;div class="service-icon"&gt; (index.html)</vh>
<v t="leo.20190426102506.145"><vh>&lt;i class="fa fa-flash"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.146"><vh>&lt;div class="service-content"&gt; (index.html)</vh>
<v t="leo.20190426102506.147"><vh>&lt;h4&gt; (index.html)</vh>
<v t="leo.20190426102506.148"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.149"><vh>&lt;p&gt; (index.html)</vh></v>
</v>
</v>
</v>
<v t="leo.20190426102506.150"><vh>&lt;div class="col-md-6 col-lg-4 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.151"><vh>&lt;div class="service-box"&gt; (index.html)</vh>
<v t="leo.20190426102506.152"><vh>&lt;div class="service-icon"&gt; (index.html)</vh>
<v t="leo.20190426102506.153"><vh>&lt;i class="fa fa-hand-pointer-o"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.154"><vh>&lt;div class="service-content"&gt; (index.html)</vh>
<v t="leo.20190426102506.155"><vh>&lt;h4&gt; (index.html)</vh>
<v t="leo.20190426102506.156"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.157"><vh>&lt;p&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.158"><vh>&lt;div class="container"&gt; (index.html)</vh>
<v t="leo.20190426102506.159"><vh>&lt;div class="row"&gt; (index.html)</vh>
<v t="leo.20190426102506.160"><vh>&lt;div class="col-md-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.161"><vh>&lt;h2 class="section-title wow fadeInDown animated" data-wow-delay="0.3s"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.162"><vh>&lt;div class="row"&gt; (index.html)</vh>
<v t="leo.20190426102506.163"><vh>&lt;div class="col-lg-12 col-md-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.164"><vh>&lt;div class="controls text-center wow fadeInUpQuick" data-wow-delay=".6s"&gt; (index.html)</vh>
<v t="leo.20190426102506.165"><vh>&lt;a class="filter active btn btn-common" data-filter="all"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.166"><vh>&lt;a class="filter btn btn-common" data-filter=".branding"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.167"><vh>&lt;a class="filter btn btn-common" data-filter=".marketing"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.168"><vh>&lt;a class="filter btn btn-common" data-filter=".planning"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.169"><vh>&lt;a class="filter btn btn-common" data-filter=".research"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.170"><vh>&lt;div class="row wow fadeInUpQuick" data-wow-delay="0.8s" id="portfolio"&gt; (index.html)</vh>
<v t="leo.20190426102506.171"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12 mix marketing planning"&gt; (index.html)</vh>
<v t="leo.20190426102506.172"><vh>&lt;div class="portfolio-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.173"><vh>&lt;div class="portfolio-img"&gt; (index.html)</vh>
<v t="leo.20190426102506.174"><vh>&lt;img alt="" src="img/portfolio/img1.jpg"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.175"><vh>&lt;div class="portfoli-content"&gt; (index.html)</vh>
<v t="leo.20190426102506.176"><vh>&lt;div class="sup-desc-wrap"&gt; (index.html)</vh>
<v t="leo.20190426102506.177"><vh>&lt;div class="sup-desc-inner"&gt; (index.html)</vh>
<v t="leo.20190426102506.178"><vh>&lt;div class="sup-link"&gt; (index.html)</vh>
<v t="leo.20190426102506.179"><vh>&lt;a class="left-link" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.180"><vh>&lt;i class="fa fa-link"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.181"><vh>&lt;a class="right-link" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.182"><vh>&lt;i class="fa fa-heart"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.183"><vh>&lt;div class="sup-meta-wrap"&gt; (index.html)</vh>
<v t="leo.20190426102506.184"><vh>&lt;a class="sup-title" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.185"><vh>&lt;h4&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.186"><vh>&lt;p class="sup-description"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.187"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12 mix branding planning"&gt; (index.html)</vh>
<v t="leo.20190426102506.188"><vh>&lt;div class="portfolio-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.189"><vh>&lt;div class="portfolio-img"&gt; (index.html)</vh>
<v t="leo.20190426102506.190"><vh>&lt;img alt="" src="img/portfolio/img2.jpg"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.191"><vh>&lt;div class="portfoli-content"&gt; (index.html)</vh>
<v t="leo.20190426102506.192"><vh>&lt;div class="sup-desc-wrap"&gt; (index.html)</vh>
<v t="leo.20190426102506.193"><vh>&lt;div class="sup-desc-inner"&gt; (index.html)</vh>
<v t="leo.20190426102506.194"><vh>&lt;div class="sup-link"&gt; (index.html)</vh>
<v t="leo.20190426102506.195"><vh>&lt;a class="left-link" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.196"><vh>&lt;i class="fa fa-link"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.197"><vh>&lt;a class="right-link" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.198"><vh>&lt;i class="fa fa-heart"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.199"><vh>&lt;div class="sup-meta-wrap"&gt; (index.html)</vh>
<v t="leo.20190426102506.200"><vh>&lt;a class="sup-title" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.201"><vh>&lt;h4&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.202"><vh>&lt;p class="sup-description"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.203"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12 mix branding research"&gt; (index.html)</vh>
<v t="leo.20190426102506.204"><vh>&lt;div class="portfolio-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.205"><vh>&lt;div class="portfolio-img"&gt; (index.html)</vh>
<v t="leo.20190426102506.206"><vh>&lt;img alt="" src="img/portfolio/img3.jpg"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.207"><vh>&lt;div class="portfoli-content"&gt; (index.html)</vh>
<v t="leo.20190426102506.208"><vh>&lt;div class="sup-desc-wrap"&gt; (index.html)</vh>
<v t="leo.20190426102506.209"><vh>&lt;div class="sup-desc-inner"&gt; (index.html)</vh>
<v t="leo.20190426102506.210"><vh>&lt;div class="sup-link"&gt; (index.html)</vh>
<v t="leo.20190426102506.211"><vh>&lt;a class="left-link" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.212"><vh>&lt;i class="fa fa-link"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.213"><vh>&lt;a class="right-link" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.214"><vh>&lt;i class="fa fa-heart"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.215"><vh>&lt;div class="sup-meta-wrap"&gt; (index.html)</vh>
<v t="leo.20190426102506.216"><vh>&lt;a class="sup-title" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.217"><vh>&lt;h4&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.218"><vh>&lt;p class="sup-description"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.219"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12 mix marketing research"&gt; (index.html)</vh>
<v t="leo.20190426102506.220"><vh>&lt;div class="portfolio-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.221"><vh>&lt;div class="portfolio-img"&gt; (index.html)</vh>
<v t="leo.20190426102506.222"><vh>&lt;img alt="" src="img/portfolio/img4.jpg"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.223"><vh>&lt;div class="portfoli-content"&gt; (index.html)</vh>
<v t="leo.20190426102506.224"><vh>&lt;div class="sup-desc-wrap"&gt; (index.html)</vh>
<v t="leo.20190426102506.225"><vh>&lt;div class="sup-desc-inner"&gt; (index.html)</vh>
<v t="leo.20190426102506.226"><vh>&lt;div class="sup-link"&gt; (index.html)</vh>
<v t="leo.20190426102506.227"><vh>&lt;a class="left-link" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.228"><vh>&lt;i class="fa fa-link"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.229"><vh>&lt;a class="right-link" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.230"><vh>&lt;i class="fa fa-heart"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.231"><vh>&lt;div class="sup-meta-wrap"&gt; (index.html)</vh>
<v t="leo.20190426102506.232"><vh>&lt;a class="sup-title" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.233"><vh>&lt;h4&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.234"><vh>&lt;p class="sup-description"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.235"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12 mix marketing planning"&gt; (index.html)</vh>
<v t="leo.20190426102506.236"><vh>&lt;div class="portfolio-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.237"><vh>&lt;div class="portfolio-img"&gt; (index.html)</vh>
<v t="leo.20190426102506.238"><vh>&lt;img alt="" src="img/portfolio/img5.jpg"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.239"><vh>&lt;div class="portfoli-content"&gt; (index.html)</vh>
<v t="leo.20190426102506.240"><vh>&lt;div class="sup-desc-wrap"&gt; (index.html)</vh>
<v t="leo.20190426102506.241"><vh>&lt;div class="sup-desc-inner"&gt; (index.html)</vh>
<v t="leo.20190426102506.242"><vh>&lt;div class="sup-link"&gt; (index.html)</vh>
<v t="leo.20190426102506.243"><vh>&lt;a class="left-link" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.244"><vh>&lt;i class="fa fa-link"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.245"><vh>&lt;a class="right-link" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.246"><vh>&lt;i class="fa fa-heart"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.247"><vh>&lt;div class="sup-meta-wrap"&gt; (index.html)</vh>
<v t="leo.20190426102506.248"><vh>&lt;a class="sup-title" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.249"><vh>&lt;h4&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.250"><vh>&lt;p class="sup-description"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.251"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12 mix planning research"&gt; (index.html)</vh>
<v t="leo.20190426102506.252"><vh>&lt;div class="portfolio-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.253"><vh>&lt;div class="portfolio-img"&gt; (index.html)</vh>
<v t="leo.20190426102506.254"><vh>&lt;img alt="" src="img/portfolio/img6.jpg"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.255"><vh>&lt;div class="portfoli-content"&gt; (index.html)</vh>
<v t="leo.20190426102506.256"><vh>&lt;div class="sup-desc-wrap"&gt; (index.html)</vh>
<v t="leo.20190426102506.257"><vh>&lt;div class="sup-desc-inner"&gt; (index.html)</vh>
<v t="leo.20190426102506.258"><vh>&lt;div class="sup-link"&gt; (index.html)</vh>
<v t="leo.20190426102506.259"><vh>&lt;a class="left-link" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.260"><vh>&lt;i class="fa fa-link"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.261"><vh>&lt;a class="right-link" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.262"><vh>&lt;i class="fa fa-heart"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.263"><vh>&lt;div class="sup-meta-wrap"&gt; (index.html)</vh>
<v t="leo.20190426102506.264"><vh>&lt;a class="sup-title" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.265"><vh>&lt;h4&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.266"><vh>&lt;p class="sup-description"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.267"><vh>&lt;div class="section-padding" id="feature"&gt; (index.html)</vh>
<v t="leo.20190426102506.268"><vh>&lt;div class="container"&gt; (index.html)</vh>
<v t="leo.20190426102506.269"><vh>&lt;div class="row"&gt; (index.html)</vh>
<v t="leo.20190426102506.270"><vh>&lt;div class="col-md-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.271"><vh>&lt;h2 class="section-title wow fadeInDown animated" data-wow-delay="0.3s"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.272"><vh>&lt;div class="row"&gt; (index.html)</vh>
<v t="leo.20190426102506.273"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.274"><vh>&lt;div class="featured-box-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.275"><vh>&lt;div class="featured-icon"&gt; (index.html)</vh>
<v t="leo.20190426102506.276"><vh>&lt;i class="fa fa-bolt"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.277"><vh>&lt;div class="featured-content"&gt; (index.html)</vh>
<v t="leo.20190426102506.278"><vh>&lt;h4&gt; (index.html)</vh></v>
<v t="leo.20190426102506.279"><vh>&lt;p&gt; (index.html)</vh></v>
</v>
</v>
</v>
<v t="leo.20190426102506.280"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.281"><vh>&lt;div class="featured-box-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.282"><vh>&lt;div class="featured-icon"&gt; (index.html)</vh>
<v t="leo.20190426102506.283"><vh>&lt;i class="fa fa-diamond"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.284"><vh>&lt;div class="featured-content"&gt; (index.html)</vh>
<v t="leo.20190426102506.285"><vh>&lt;h4&gt; (index.html)</vh></v>
<v t="leo.20190426102506.286"><vh>&lt;p&gt; (index.html)</vh></v>
</v>
</v>
</v>
<v t="leo.20190426102506.287"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.288"><vh>&lt;div class="featured-box-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.289"><vh>&lt;div class="featured-icon"&gt; (index.html)</vh>
<v t="leo.20190426102506.290"><vh>&lt;i class="fa fa-cubes"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.291"><vh>&lt;div class="featured-content"&gt; (index.html)</vh>
<v t="leo.20190426102506.292"><vh>&lt;h4&gt; (index.html)</vh></v>
<v t="leo.20190426102506.293"><vh>&lt;p&gt; (index.html)</vh></v>
</v>
</v>
</v>
<v t="leo.20190426102506.294"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.295"><vh>&lt;div class="featured-box-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.296"><vh>&lt;div class="featured-icon"&gt; (index.html)</vh>
<v t="leo.20190426102506.297"><vh>&lt;i class="fa fa-cogs"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.298"><vh>&lt;div class="featured-content"&gt; (index.html)</vh>
<v t="leo.20190426102506.299"><vh>&lt;h4&gt; (index.html)</vh></v>
<v t="leo.20190426102506.300"><vh>&lt;p&gt; (index.html)</vh></v>
</v>
</v>
</v>
<v t="leo.20190426102506.301"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.302"><vh>&lt;div class="featured-box-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.303"><vh>&lt;div class="featured-icon"&gt; (index.html)</vh>
<v t="leo.20190426102506.304"><vh>&lt;i class="fa fa-check"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.305"><vh>&lt;div class="featured-content"&gt; (index.html)</vh>
<v t="leo.20190426102506.306"><vh>&lt;h4&gt; (index.html)</vh></v>
<v t="leo.20190426102506.307"><vh>&lt;p&gt; (index.html)</vh></v>
</v>
</v>
</v>
<v t="leo.20190426102506.308"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.309"><vh>&lt;div class="featured-box-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.310"><vh>&lt;div class="featured-icon"&gt; (index.html)</vh>
<v t="leo.20190426102506.311"><vh>&lt;i class="fa fa-cloud"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.312"><vh>&lt;div class="featured-content"&gt; (index.html)</vh>
<v t="leo.20190426102506.313"><vh>&lt;h4&gt; (index.html)</vh></v>
<v t="leo.20190426102506.314"><vh>&lt;p&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.315"><vh>&lt;div id="counter"&gt; (index.html)</vh>
<v t="leo.20190426102506.316"><vh>&lt;div class="container"&gt; (index.html)</vh>
<v t="leo.20190426102506.317"><vh>&lt;div class="row count-to-sec"&gt; (index.html)</vh>
<v t="leo.20190426102506.318"><vh>&lt;div class="col-lg-3 col-md-6 col-xs-12 count-one"&gt; (index.html)</vh>
<v t="leo.20190426102506.319"><vh>&lt;span class="icon"&gt; (index.html)</vh>
<v t="leo.20190426102506.320"><vh>&lt;i class="fa fa-download"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.321"><vh>&lt;h3 class="timer count-value" data-speed="1000" data-to="561"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.322"><vh>&lt;small class="count-title"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.323"><vh>&lt;div class="col-lg-3 col-md-6 col-xs-12 count-one"&gt; (index.html)</vh>
<v t="leo.20190426102506.324"><vh>&lt;span class="icon"&gt; (index.html)</vh>
<v t="leo.20190426102506.325"><vh>&lt;i class="fa fa-user"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.326"><vh>&lt;h3 class="timer count-value" data-speed="1000" data-to="950"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.327"><vh>&lt;small class="count-title"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.328"><vh>&lt;div class="col-lg-3 col-md-6 col-xs-12 count-one"&gt; (index.html)</vh>
<v t="leo.20190426102506.329"><vh>&lt;span class="icon"&gt; (index.html)</vh>
<v t="leo.20190426102506.330"><vh>&lt;i class="fa fa-desktop"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.331"><vh>&lt;h3 class="timer count-value" data-speed="1000" data-to="978"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.332"><vh>&lt;small class="count-title"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.333"><vh>&lt;div class="col-lg-3 col-md-6 col-xs-12 count-one"&gt; (index.html)</vh>
<v t="leo.20190426102506.334"><vh>&lt;span class="icon"&gt; (index.html)</vh>
<v t="leo.20190426102506.335"><vh>&lt;i class="fa fa-coffee"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.336"><vh>&lt;h3 class="timer count-value" data-speed="1000" data-to="1700"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.337"><vh>&lt;small class="count-title"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.338"><vh>&lt;div class="team-members-tow section-padding" id="team"&gt; (index.html)</vh>
<v t="leo.20190426102506.339"><vh>&lt;div class="container"&gt; (index.html)</vh>
<v t="leo.20190426102506.340"><vh>&lt;div class="row"&gt; (index.html)</vh>
<v t="leo.20190426102506.341"><vh>&lt;div class="col-md-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.342"><vh>&lt;h2 class="section-title wow fadeInDown animated" data-wow-delay="0.3s"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.343"><vh>&lt;div class="row"&gt; (index.html)</vh>
<v t="leo.20190426102506.344"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.345"><vh>&lt;div class="image-overlay"&gt; (index.html)</vh>
<v t="leo.20190426102506.346"><vh>&lt;div class="overlay-text text-center"&gt; (index.html)</vh>
<v t="leo.20190426102506.347"><vh>&lt;div class="info-text"&gt; (index.html)</vh>
<v t="leo.20190426102506.348"><vh>&lt;strong&gt; (index.html)</vh></v>
<v t="leo.20190426102506.349"><vh>&lt;span&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.350"><vh>&lt;ul class="social-icons"&gt; (index.html)</vh>
<v t="leo.20190426102506.351"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.352"><vh>&lt;a href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.353"><vh>&lt;i aria-hidden="true" class="fa fa-facebook"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.354"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.355"><vh>&lt;a href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.356"><vh>&lt;i aria-hidden="true" class="fa fa-twitter"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.357"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.358"><vh>&lt;a href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.359"><vh>&lt;i aria-hidden="true" class="fa fa-instagram"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.360"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.361"><vh>&lt;div class="image-overlay"&gt; (index.html)</vh>
<v t="leo.20190426102506.362"><vh>&lt;div class="overlay-text text-center"&gt; (index.html)</vh>
<v t="leo.20190426102506.363"><vh>&lt;div class="info-text"&gt; (index.html)</vh>
<v t="leo.20190426102506.364"><vh>&lt;strong&gt; (index.html)</vh></v>
<v t="leo.20190426102506.365"><vh>&lt;span&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.366"><vh>&lt;ul class="social-icons"&gt; (index.html)</vh>
<v t="leo.20190426102506.367"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.368"><vh>&lt;a href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.369"><vh>&lt;i aria-hidden="true" class="fa fa-facebook"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.370"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.371"><vh>&lt;a href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.372"><vh>&lt;i aria-hidden="true" class="fa fa-twitter"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.373"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.374"><vh>&lt;a href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.375"><vh>&lt;i aria-hidden="true" class="fa fa-instagram"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.376"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.377"><vh>&lt;div class="image-overlay"&gt; (index.html)</vh>
<v t="leo.20190426102506.378"><vh>&lt;div class="overlay-text text-center"&gt; (index.html)</vh>
<v t="leo.20190426102506.379"><vh>&lt;div class="info-text"&gt; (index.html)</vh>
<v t="leo.20190426102506.380"><vh>&lt;strong&gt; (index.html)</vh></v>
<v t="leo.20190426102506.381"><vh>&lt;span&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.382"><vh>&lt;ul class="social-icons"&gt; (index.html)</vh>
<v t="leo.20190426102506.383"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.384"><vh>&lt;a href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.385"><vh>&lt;i aria-hidden="true" class="fa fa-facebook"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.386"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.387"><vh>&lt;a href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.388"><vh>&lt;i aria-hidden="true" class="fa fa-twitter"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.389"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.390"><vh>&lt;a href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.391"><vh>&lt;i aria-hidden="true" class="fa fa-instagram"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.392"><vh>&lt;div class="container"&gt; (index.html)</vh>
<v t="leo.20190426102506.393"><vh>&lt;div class="row"&gt; (index.html)</vh>
<v t="leo.20190426102506.394"><vh>&lt;div class="col-md-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.395"><vh>&lt;h2 class="section-title wow fadeInDown animated" data-wow-delay="0.3s"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.396"><vh>&lt;div class="row"&gt; (index.html)</vh>
<v t="leo.20190426102506.397"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.398"><vh>&lt;div class="pricing-table-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.399"><vh>&lt;div class="plan-name"&gt; (index.html)</vh>
<v t="leo.20190426102506.400"><vh>&lt;h3&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.401"><vh>&lt;div class="plan-price"&gt; (index.html)</vh>
<v t="leo.20190426102506.402"><vh>&lt;div class="price-value"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.403"><vh>&lt;div class="interval"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.404"><vh>&lt;div class="plan-list"&gt; (index.html)</vh>
<v t="leo.20190426102506.405"><vh>&lt;ul&gt; (index.html)</vh>
<v t="leo.20190426102506.406"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.407"><vh>&lt;i class="fa fa-check"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.408"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.409"><vh>&lt;i class="fa fa-check"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.410"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.411"><vh>&lt;i class="fa fa-check"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.412"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.413"><vh>&lt;i class="fa fa-check"&gt; (index.html)</vh></v>
</v>
</v>
</v>
<v t="leo.20190426102506.414"><vh>&lt;div class="plan-signup"&gt; (index.html)</vh>
<v t="leo.20190426102506.415"><vh>&lt;a class="btn btn-common" href="#"&gt; (index.html)</vh></v>
</v>
</v>
</v>
<v t="leo.20190426102506.416"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.417"><vh>&lt;div class="pricing-table-item table-active"&gt; (index.html)</vh>
<v t="leo.20190426102506.418"><vh>&lt;div class="plan-name"&gt; (index.html)</vh>
<v t="leo.20190426102506.419"><vh>&lt;h3&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.420"><vh>&lt;div class="plan-price"&gt; (index.html)</vh>
<v t="leo.20190426102506.421"><vh>&lt;div class="price-value"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.422"><vh>&lt;div class="interval"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.423"><vh>&lt;div class="plan-list"&gt; (index.html)</vh>
<v t="leo.20190426102506.424"><vh>&lt;ul&gt; (index.html)</vh>
<v t="leo.20190426102506.425"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.426"><vh>&lt;i class="fa fa-check"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.427"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.428"><vh>&lt;i class="fa fa-check"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.429"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.430"><vh>&lt;i class="fa fa-check"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.431"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.432"><vh>&lt;i class="fa fa-check"&gt; (index.html)</vh></v>
</v>
</v>
</v>
<v t="leo.20190426102506.433"><vh>&lt;div class="plan-signup"&gt; (index.html)</vh>
<v t="leo.20190426102506.434"><vh>&lt;a class="btn btn-common" href="#"&gt; (index.html)</vh></v>
</v>
</v>
</v>
<v t="leo.20190426102506.435"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.436"><vh>&lt;div class="pricing-table-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.437"><vh>&lt;div class="plan-name"&gt; (index.html)</vh>
<v t="leo.20190426102506.438"><vh>&lt;h3&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.439"><vh>&lt;div class="plan-price"&gt; (index.html)</vh>
<v t="leo.20190426102506.440"><vh>&lt;div class="price-value"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.441"><vh>&lt;div class="interval"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.442"><vh>&lt;div class="plan-list"&gt; (index.html)</vh>
<v t="leo.20190426102506.443"><vh>&lt;ul&gt; (index.html)</vh>
<v t="leo.20190426102506.444"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.445"><vh>&lt;i class="fa fa-check"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.446"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.447"><vh>&lt;i class="fa fa-check"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.448"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.449"><vh>&lt;i class="fa fa-check"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.450"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.451"><vh>&lt;i class="fa fa-check"&gt; (index.html)</vh></v>
</v>
</v>
</v>
<v t="leo.20190426102506.452"><vh>&lt;div class="plan-signup"&gt; (index.html)</vh>
<v t="leo.20190426102506.453"><vh>&lt;a class="btn btn-common" href="#"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.454"><vh>&lt;div class="single-testimonial-area"&gt; (index.html)</vh>
<v t="leo.20190426102506.455"><vh>&lt;div class="container"&gt; (index.html)</vh>
<v t="leo.20190426102506.456"><vh>&lt;div class="owl-carousel" id="single-testimonial-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.457"><vh>&lt;div class="item"&gt; (index.html)</vh>
<v t="leo.20190426102506.458"><vh>&lt;div class="row justify-content-md-center"&gt; (index.html)</vh>
<v t="leo.20190426102506.459"><vh>&lt;div class="col-lg-8 col-md-12 col-xs-12 col-md-auto"&gt; (index.html)</vh>
<v t="leo.20190426102506.460"><vh>&lt;div class="testimonial-inner text-md-center"&gt; (index.html)</vh>
<v t="leo.20190426102506.461"><vh>&lt;blockquote&gt; (index.html)</vh></v>
<v t="leo.20190426102506.462"><vh>&lt;div class="testimonial-images"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.463"><vh>&lt;div class="testimonial-footer"&gt; (index.html)</vh>
<v t="leo.20190426102506.464"><vh>&lt;i class="fa fa-user"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.465"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.466"><vh>&lt;div class="item"&gt; (index.html)</vh>
<v t="leo.20190426102506.467"><vh>&lt;div class="row justify-content-md-center"&gt; (index.html)</vh>
<v t="leo.20190426102506.468"><vh>&lt;div class="col-lg-8 col-md-12 col-xs-12 col-md-auto"&gt; (index.html)</vh>
<v t="leo.20190426102506.469"><vh>&lt;div class="testimonial-inner text-md-center"&gt; (index.html)</vh>
<v t="leo.20190426102506.470"><vh>&lt;blockquote&gt; (index.html)</vh></v>
<v t="leo.20190426102506.471"><vh>&lt;div class="testimonial-images"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.472"><vh>&lt;div class="testimonial-footer"&gt; (index.html)</vh>
<v t="leo.20190426102506.473"><vh>&lt;i class="fa fa-user"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.474"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.475"><vh>&lt;div class="item"&gt; (index.html)</vh>
<v t="leo.20190426102506.476"><vh>&lt;div class="row justify-content-md-center"&gt; (index.html)</vh>
<v t="leo.20190426102506.477"><vh>&lt;div class="col-lg-8 col-md-12 col-xs-12 col-md-auto"&gt; (index.html)</vh>
<v t="leo.20190426102506.478"><vh>&lt;div class="testimonial-inner text-md-center"&gt; (index.html)</vh>
<v t="leo.20190426102506.479"><vh>&lt;blockquote&gt; (index.html)</vh></v>
<v t="leo.20190426102506.480"><vh>&lt;div class="testimonial-images"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.481"><vh>&lt;div class="testimonial-footer"&gt; (index.html)</vh>
<v t="leo.20190426102506.482"><vh>&lt;i class="fa fa-user"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.483"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.484"><vh>&lt;div class="container"&gt; (index.html)</vh>
<v t="leo.20190426102506.485"><vh>&lt;div class="row"&gt; (index.html)</vh>
<v t="leo.20190426102506.486"><vh>&lt;div class="col-md-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.487"><vh>&lt;h2 class="section-title wow fadeInDown animated" data-wow-delay="0.3s"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.488"><vh>&lt;div class="row"&gt; (index.html)</vh>
<v t="leo.20190426102506.489"><vh>&lt;div class="col-lg-8 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.490"><vh>&lt;h3 class="title-head text-left"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.491"><vh>&lt;form class="contact-form" data-toggle="validator"&gt; (index.html)</vh>
<v t="leo.20190426102506.492"><vh>&lt;div class="row"&gt; (index.html)</vh>
<v t="leo.20190426102506.493"><vh>&lt;div class="col-lg-4 col-md-12 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.494"><vh>&lt;div class="form-group"&gt; (index.html)</vh>
<v t="leo.20190426102506.495"><vh>&lt;i class="contact-icon fa fa-user"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.496"><vh>&lt;div class="help-block with-errors"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.497"><vh>&lt;div class="col-lg-4 col-md-12 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.498"><vh>&lt;div class="form-group"&gt; (index.html)</vh>
<v t="leo.20190426102506.499"><vh>&lt;i class="contact-icon fa fa-envelope-o"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.500"><vh>&lt;div class="help-block with-errors"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.501"><vh>&lt;div class="col-lg-4 col-md-12 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.502"><vh>&lt;div class="form-group"&gt; (index.html)</vh>
<v t="leo.20190426102506.503"><vh>&lt;i class="contact-icon fa fa-pencil-square-o"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.504"><vh>&lt;div class="help-block with-errors"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.505"><vh>&lt;div class="col-lg-12 col-md-12 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.506"><vh>&lt;div class="help-block with-errors"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.507"><vh>&lt;button class="btn btn-common btn-form-submit" id="form-submit" type="submit"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.508"><vh>&lt;div class="h3 text-center hidden" id="msgSubmit"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.509"><vh>&lt;div class="clearfix"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.510"><vh>&lt;div class="col-lg-4 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.511"><vh>&lt;h4 class="contact-info-title text-left"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.512"><vh>&lt;div class="contact-info"&gt; (index.html)</vh>
<v t="leo.20190426102506.513"><vh>&lt;address&gt; (index.html)</vh>
<v t="leo.20190426102506.514"><vh>&lt;i class="lni-map-marker icons cyan-color contact-info-icon"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.515"><vh>&lt;div class="tel-info"&gt; (index.html)</vh>
<v t="leo.20190426102506.516"><vh>&lt;a href="tel:1800452308"&gt; (index.html)</vh>
<v t="leo.20190426102506.517"><vh>&lt;i class="lni-mobile icons cyan-color contact-info-icon"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.518"><vh>&lt;a href="tel:+61(8)82343555"&gt; (index.html)</vh>
<v t="leo.20190426102506.519"><vh>&lt;i class="lni-phone icons cyan-color contact-info-icon"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.520"><vh>&lt;a href="mailto:hello@spiritapp.com"&gt; (index.html)</vh>
<v t="leo.20190426102506.521"><vh>&lt;i class="lni-envelope icons cyan-color contact-info-icon"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.522"><vh>&lt;a href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.523"><vh>&lt;i class="lni-tab icons cyan-color contact-info-icon"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.524"><vh>&lt;ul class="social-links"&gt; (index.html)</vh>
<v t="leo.20190426102506.525"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.526"><vh>&lt;a class="fa fa-facebook" href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.527"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.528"><vh>&lt;a class="fa fa-twitter" href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.529"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.530"><vh>&lt;a class="fa fa-instagram" href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.531"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.532"><vh>&lt;a class="fa fa-linkedin" href="#"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.533"><vh>&lt;div class="container"&gt; (index.html)</vh>
<v t="leo.20190426102506.534"><vh>&lt;div class="row section"&gt; (index.html)</vh>
<v t="leo.20190426102506.535"><vh>&lt;div class="footer-widget col-lg-3 col-md-6 col-xs-12 wow fadeIn"&gt; (index.html)</vh>
<v t="leo.20190426102506.536"><vh>&lt;h3 class="small-title"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.537"><vh>&lt;p&gt; (index.html)</vh></v>
<v t="leo.20190426102506.538"><vh>&lt;div class="social-footer"&gt; (index.html)</vh>
<v t="leo.20190426102506.539"><vh>&lt;a href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.540"><vh>&lt;i class="fa fa-facebook icon-round"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.541"><vh>&lt;a href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.542"><vh>&lt;i class="fa fa-twitter icon-round"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.543"><vh>&lt;a href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.544"><vh>&lt;i class="fa fa-linkedin icon-round"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.545"><vh>&lt;a href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.546"><vh>&lt;i class="fa fa-google-plus icon-round"&gt; (index.html)</vh></v>
</v>
</v>
</v>
<v t="leo.20190426102506.547"><vh>&lt;div class="footer-widget col-lg-3 col-md-6 col-xs-12 wow fadeIn" data-wow-delay=".2s"&gt; (index.html)</vh>
<v t="leo.20190426102506.548"><vh>&lt;h3 class="small-title"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.549"><vh>&lt;ul class="menu"&gt; (index.html)</vh>
<v t="leo.20190426102506.550"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.551"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.552"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.553"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.554"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.555"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.556"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.557"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.558"><vh>&lt;li&gt; (index.html)</vh>
<v t="leo.20190426102506.559"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
</v>
</v>
<v t="leo.20190426102506.560"><vh>&lt;div class="footer-widget col-lg-3 col-md-6 col-xs-12 wow fadeIn" data-wow-delay=".5s"&gt; (index.html)</vh>
<v t="leo.20190426102506.561"><vh>&lt;h3 class="small-title"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.562"><vh>&lt;div class="plain-flicker-gallery"&gt; (index.html)</vh>
<v t="leo.20190426102506.563"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.564"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.565"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.566"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.567"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.568"><vh>&lt;a href="#"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.569"><vh>&lt;div class="footer-widget col-lg-3 col-md-6 col-xs-12 wow fadeIn" data-wow-delay=".8s"&gt; (index.html)</vh>
<v t="leo.20190426102506.570"><vh>&lt;h3 class="small-title"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.571"><vh>&lt;div class="contact-us"&gt; (index.html)</vh>
<v t="leo.20190426102506.572"><vh>&lt;form&gt; (index.html)</vh>
<v t="leo.20190426102506.573"><vh>&lt;div class="form-group"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.574"><vh>&lt;div class="form-group"&gt; (index.html)</vh></v>
<v t="leo.20190426102506.575"><vh>&lt;button class="btn btn-common" type="submit"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.576"><vh>&lt;div id="copyright"&gt; (index.html)</vh>
<v t="leo.20190426102506.577"><vh>&lt;div class="container"&gt; (index.html)</vh>
<v t="leo.20190426102506.578"><vh>&lt;div class="row"&gt; (index.html)</vh>
<v t="leo.20190426102506.579"><vh>&lt;div class="col-lg-6 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.580"><vh>&lt;p class="copyright-text"&gt; (index.html)</vh>
<v t="leo.20190426102506.581"><vh>&lt;a href="https://uideck.com" rel="nofollow"&gt; (index.html)</vh></v>
</v>
</v>
<v t="leo.20190426102506.582"><vh>&lt;div class="col-lg-6 col-md-6 col-xs-12"&gt; (index.html)</vh>
<v t="leo.20190426102506.583"><vh>&lt;ul class="nav nav-inline justify-content-end"&gt; (index.html)</vh>
<v t="leo.20190426102506.584"><vh>&lt;li class="nav-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.585"><vh>&lt;a class="nav-link active" href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.586"><vh>&lt;li class="nav-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.587"><vh>&lt;a class="nav-link" href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.588"><vh>&lt;li class="nav-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.589"><vh>&lt;a class="nav-link" href="#"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.590"><vh>&lt;li class="nav-item"&gt; (index.html)</vh>
<v t="leo.20190426102506.591"><vh>&lt;a class="nav-link" href="#"&gt; (index.html)</vh></v>
</v>
</v>
</v>
</v>
</v>
</v>
<v t="leo.20190426102506.592"><vh>&lt;a class="back-to-top" href="#"&gt; (index.html)</vh>
<v t="leo.20190426102506.593"><vh>&lt;i class="fa fa-arrow-up"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102506.594"><vh>&lt;div id="preloader"&gt; (index.html)</vh>
<v t="leo.20190426102506.595"><vh>&lt;div class="loader" id="loader-1"&gt; (index.html)</vh></v>
</v>
<v t="leo.20190426102601.1"><vh>Scripts</vh></v>
</v>
</v>
</v>
</vnodes>
<tnodes>
<t tx="leo.20190426102408.2">&lt;!DOCTYPE html&gt;
@others
@language xml
@tabwidth -4
</t>
<t tx="leo.20190426102417.1"></t>
<t tx="leo.20190426102417.2">QTreeWidget {
    /* These apply to the selected item, but not to editing items.*/
    background-color: #ffffec; /* Leo's traditional tree color */
    selection-color: black; /* was white */
    selection-background-color: lightgrey;
    /* font-family: SansSerif; */
    /*font-family: DejaVu Sans Mono;*/
    font-family:YaHei Mono;
    /* 標題字型大小設定 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
 }

/* Headline edit widgets */
QTreeWidget QLineEdit {
    background-color: cornsilk;
    selection-color: white;
    selection-background-color: blue;
    /*font-family: DejaVu Sans Mono;*/    
    font-family:YaHei Mono;
    /* 沒有特別對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The log panes */
QTextEdit {
    background-color: #f2fdff;
    selection-color: red;
    selection-background-color: blue;
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* log font 大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal, italic,oblique */
}

/* The body pane */
QTextEdit#richTextEdit {
    background-color: #fdf5f5; /* A kind of pink. */
    selection-color: white;
    selection-background-color: red;
    /*font-family: DejaVu Sans Mono;*/
    /* font-family: Courier New; */
    font-family:YaHei Mono;
    /* 內文字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

QLabel {
    font-family:YaHei Mono;'CherryPy', 'pytz', 'mako', 'beautifulsoup4', 'pymysql', 'peewee'
    /* 下方的 Minibuffer 標題字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
}

/* Editor labels */
QLineEdit#editorLabel {
    background-color: #ffffec;
    font-family:YaHei Mono;
    /* 沒有直接對應字型大小 */
    font-size: 20px;
    font-weight: normal; /* normal,bold,100,..,900 */
    font-style: normal; /* normal,italic,oblique */
    border: 2px;
    margin: 2px;
}</t>
<t tx="leo.20190426102417.3">horizontal: body pane to the left
vertical: body pane on the botton</t>
<t tx="leo.20190426102506.1">&lt;html lang="en"&gt;
    @others
&lt;/html&gt;
</t>
<t tx="leo.20190426102506.10">       &lt;span class="icon-menu"&gt;
       &lt;/span&gt;
</t>
<t tx="leo.20190426102506.100">     &lt;div class="col-lg-3 col-md-6 col-xs-12"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.101">      &lt;div class="about block text-center"&gt;
       &lt;img alt="" src="img/about/img4.png"/&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.102">       &lt;h5&gt;
    @others
       &lt;/h5&gt;
</t>
<t tx="leo.20190426102506.103">        &lt;a href="#"&gt;
         About Title
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.104">       &lt;p&gt;
        Quisque sit amet libero purus. Nulla a dignissim quam. In hac habitasse platea dictumst.
       &lt;/p&gt;
</t>
<t tx="leo.20190426102506.105">   &lt;div class="container"&gt;
    @others
   &lt;/div&gt;
  &lt;/section&gt;
  &lt;!-- Services Section End --&gt;
  &lt;!-- Portfolio Section --&gt;
  &lt;section class="section-padding" id="portfolio"&gt;
   &lt;!-- Container Starts --&gt;
</t>
<t tx="leo.20190426102506.106">    &lt;div class="row"&gt;
    @others
    &lt;/div&gt;
</t>
<t tx="leo.20190426102506.107">     &lt;div class="col-md-12"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.108">      &lt;h2 class="section-title wow fadeInDown animated" data-wow-delay="0.3s"&gt;
       Our Services
      &lt;/h2&gt;
</t>
<t tx="leo.20190426102506.109">    &lt;div class="row"&gt;
     &lt;!-- Start Service Icon 1 --&gt;
    @others
    &lt;/div&gt;
</t>
<t tx="leo.20190426102506.11">       &lt;span class="icon-menu"&gt;
       &lt;/span&gt;
</t>
<t tx="leo.20190426102506.110">     &lt;div class="col-md-6 col-lg-4 col-xs-12"&gt;
    @others
     &lt;/div&gt;
     &lt;!-- End Service Icon 1 --&gt;
     &lt;!-- Start Service Icon 2 --&gt;
</t>
<t tx="leo.20190426102506.111">      &lt;div class="service-box"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.112">       &lt;div class="service-icon"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.113">        &lt;i class="fa fa-cogs"&gt;
        &lt;/i&gt;
</t>
<t tx="leo.20190426102506.114">       &lt;div class="service-content"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.115">        &lt;h4&gt;
    @others
        &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.116">         &lt;a href="#"&gt;
          Easy to Customize
         &lt;/a&gt;
</t>
<t tx="leo.20190426102506.117">        &lt;p&gt;
         Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae architecto officiis consequuntur vero error excepturi.
        &lt;/p&gt;
</t>
<t tx="leo.20190426102506.118">     &lt;div class="col-md-6 col-lg-4 col-xs-12"&gt;
    @others
     &lt;/div&gt;
     &lt;!-- End Service Icon 2 --&gt;
     &lt;!-- Start Service Icon 3 --&gt;
</t>
<t tx="leo.20190426102506.119">      &lt;div class="service-box"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.12">      &lt;a class="navbar-brand" href="index.html"&gt;
       &lt;img alt="" src="img/logo.png"/&gt;
      &lt;/a&gt;
</t>
<t tx="leo.20190426102506.120">       &lt;div class="service-icon"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.121">        &lt;i class="fa fa-cubes"&gt;
        &lt;/i&gt;
</t>
<t tx="leo.20190426102506.122">       &lt;div class="service-content"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.123">        &lt;h4&gt;
    @others
        &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.124">         &lt;a href="#"&gt;
          100+ Components
         &lt;/a&gt;
</t>
<t tx="leo.20190426102506.125">        &lt;p&gt;
         Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae architecto officiis consequuntur vero error excepturi.
        &lt;/p&gt;
</t>
<t tx="leo.20190426102506.126">     &lt;div class="col-md-6 col-lg-4 col-xs-12"&gt;
    @others
     &lt;/div&gt;
     &lt;!-- End Service Icon 3 --&gt;
     &lt;!-- Start Service Icon 4 --&gt;
</t>
<t tx="leo.20190426102506.127">      &lt;div class="service-box"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.128">       &lt;div class="service-icon"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.129">        &lt;i class="fa fa-tachometer"&gt;
        &lt;/i&gt;
</t>
<t tx="leo.20190426102506.13">     &lt;div class="collapse navbar-collapse" id="main-navbar"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.130">       &lt;div class="service-content"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.131">        &lt;h4&gt;
    @others
        &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.132">         &lt;a href="#"&gt;
          Super Fast
         &lt;/a&gt;
</t>
<t tx="leo.20190426102506.133">        &lt;p&gt;
         Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae architecto officiis consequuntur vero error excepturi.
        &lt;/p&gt;
</t>
<t tx="leo.20190426102506.134">     &lt;div class="col-md-6 col-lg-4 col-xs-12"&gt;
    @others
     &lt;/div&gt;
     &lt;!-- End Service Icon 4 --&gt;
     &lt;!-- Start Service Icon 5 --&gt;
</t>
<t tx="leo.20190426102506.135">      &lt;div class="service-box"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.136">       &lt;div class="service-icon"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.137">        &lt;i class="fa fa-check"&gt;
        &lt;/i&gt;
</t>
<t tx="leo.20190426102506.138">       &lt;div class="service-content"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.139">        &lt;h4&gt;
    @others
        &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.14">      &lt;ul class="navbar-nav mr-auto w-100 justify-content-end clearfix"&gt;
    @others
      &lt;/ul&gt;
</t>
<t tx="leo.20190426102506.140">         &lt;a href="#"&gt;
          Clean Design
         &lt;/a&gt;
</t>
<t tx="leo.20190426102506.141">        &lt;p&gt;
         Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae architecto officiis consequuntur vero error excepturi.
        &lt;/p&gt;
</t>
<t tx="leo.20190426102506.142">     &lt;div class="col-md-6 col-lg-4 col-xs-12"&gt;
    @others
     &lt;/div&gt;
     &lt;!-- End Service Icon 5 --&gt;
     &lt;!-- Start Service Icon 6 --&gt;
</t>
<t tx="leo.20190426102506.143">      &lt;div class="service-box"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.144">       &lt;div class="service-icon"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.145">        &lt;i class="fa fa-flash"&gt;
        &lt;/i&gt;
</t>
<t tx="leo.20190426102506.146">       &lt;div class="service-content"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.147">        &lt;h4&gt;
    @others
        &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.148">         &lt;a href="#"&gt;
          Bootstrap 4 UI Kit
         &lt;/a&gt;
</t>
<t tx="leo.20190426102506.149">        &lt;p&gt;
         Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae architecto officiis consequuntur vero error excepturi.
        &lt;/p&gt;
</t>
<t tx="leo.20190426102506.15">       &lt;li class="nav-item active"&gt;
    @others
       &lt;/li&gt;
</t>
<t tx="leo.20190426102506.150">     &lt;div class="col-md-6 col-lg-4 col-xs-12"&gt;
    @others
     &lt;/div&gt;
     &lt;!-- End Service Icon 6 --&gt;
</t>
<t tx="leo.20190426102506.151">      &lt;div class="service-box"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.152">       &lt;div class="service-icon"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.153">        &lt;i class="fa fa-hand-pointer-o"&gt;
        &lt;/i&gt;
</t>
<t tx="leo.20190426102506.154">       &lt;div class="service-content"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.155">        &lt;h4&gt;
    @others
        &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.156">         &lt;a href="#"&gt;
          Advanced Features
         &lt;/a&gt;
</t>
<t tx="leo.20190426102506.157">        &lt;p&gt;
         Lorem ipsum dolor sit amet, consectetur adipisicing elit. Recusandae architecto officiis consequuntur vero error excepturi.
        &lt;/p&gt;
</t>
<t tx="leo.20190426102506.158">   &lt;div class="container"&gt;
    @others
   &lt;/div&gt;
   &lt;!-- Container Ends --&gt;
  &lt;/section&gt;
  &lt;!-- Portfolio Section Ends --&gt;
  &lt;!-- Feature Section Start --&gt;
</t>
<t tx="leo.20190426102506.159">    &lt;div class="row"&gt;
    @others
    &lt;/div&gt;
</t>
<t tx="leo.20190426102506.16">        &lt;a class="nav-link" href="#sliders"&gt;
         Home
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.160">     &lt;div class="col-md-12"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.161">      &lt;h2 class="section-title wow fadeInDown animated" data-wow-delay="0.3s"&gt;
       Portfolio
      &lt;/h2&gt;
</t>
<t tx="leo.20190426102506.162">    &lt;div class="row"&gt;
    @others
    &lt;/div&gt;
</t>
<t tx="leo.20190426102506.163">     &lt;div class="col-lg-12 col-md-12"&gt;
      &lt;!-- Portfolio Controller/Buttons --&gt;
    @others
     &lt;/div&gt;
     &lt;!-- Portfolio Recent Projects --&gt;
</t>
<t tx="leo.20190426102506.164">      &lt;div class="controls text-center wow fadeInUpQuick" data-wow-delay=".6s"&gt;
    @others
      &lt;/div&gt;
      &lt;!-- Portfolio Controller/Buttons Ends--&gt;
</t>
<t tx="leo.20190426102506.165">       &lt;a class="filter active btn btn-common" data-filter="all"&gt;
        All
       &lt;/a&gt;
</t>
<t tx="leo.20190426102506.166">       &lt;a class="filter btn btn-common" data-filter=".branding"&gt;
        Branding
       &lt;/a&gt;
</t>
<t tx="leo.20190426102506.167">       &lt;a class="filter btn btn-common" data-filter=".marketing"&gt;
        Marketing
       &lt;/a&gt;
</t>
<t tx="leo.20190426102506.168">       &lt;a class="filter btn btn-common" data-filter=".planning"&gt;
        Planning
       &lt;/a&gt;
</t>
<t tx="leo.20190426102506.169">       &lt;a class="filter btn btn-common" data-filter=".research"&gt;
        Research
       &lt;/a&gt;
</t>
<t tx="leo.20190426102506.17">       &lt;li class="nav-item"&gt;
    @others
       &lt;/li&gt;
</t>
<t tx="leo.20190426102506.170">     &lt;div class="row wow fadeInUpQuick" data-wow-delay="0.8s" id="portfolio"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.171">      &lt;div class="col-lg-4 col-md-6 col-xs-12 mix marketing planning"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.172">       &lt;div class="portfolio-item"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.173">        &lt;div class="portfolio-img"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.174">         &lt;img alt="" src="img/portfolio/img1.jpg"&gt;
         &lt;/img&gt;
</t>
<t tx="leo.20190426102506.175">        &lt;div class="portfoli-content"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.176">         &lt;div class="sup-desc-wrap"&gt;
    @others
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.177">          &lt;div class="sup-desc-inner"&gt;
    @others
          &lt;/div&gt;
</t>
<t tx="leo.20190426102506.178">           &lt;div class="sup-link"&gt;
    @others
           &lt;/div&gt;
</t>
<t tx="leo.20190426102506.179">            &lt;a class="left-link" href="#"&gt;
    @others
            &lt;/a&gt;
</t>
<t tx="leo.20190426102506.18">        &lt;a class="nav-link" href="#about"&gt;
         About
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.180">             &lt;i class="fa fa-link"&gt;
             &lt;/i&gt;
</t>
<t tx="leo.20190426102506.181">            &lt;a class="right-link" href="#"&gt;
    @others
            &lt;/a&gt;
</t>
<t tx="leo.20190426102506.182">             &lt;i class="fa fa-heart"&gt;
             &lt;/i&gt;
</t>
<t tx="leo.20190426102506.183">           &lt;div class="sup-meta-wrap"&gt;
    @others
           &lt;/div&gt;
</t>
<t tx="leo.20190426102506.184">            &lt;a class="sup-title" href="#"&gt;
    @others
            &lt;/a&gt;
</t>
<t tx="leo.20190426102506.185">             &lt;h4&gt;
              TITLE HERE
             &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.186">            &lt;p class="sup-description"&gt;
             Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente vel quisquam.
            &lt;/p&gt;
</t>
<t tx="leo.20190426102506.187">      &lt;div class="col-lg-4 col-md-6 col-xs-12 mix branding planning"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.188">       &lt;div class="portfolio-item"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.189">        &lt;div class="portfolio-img"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.19">       &lt;li class="nav-item"&gt;
    @others
       &lt;/li&gt;
</t>
<t tx="leo.20190426102506.190">         &lt;img alt="" src="img/portfolio/img2.jpg"&gt;
         &lt;/img&gt;
</t>
<t tx="leo.20190426102506.191">        &lt;div class="portfoli-content"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.192">         &lt;div class="sup-desc-wrap"&gt;
    @others
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.193">          &lt;div class="sup-desc-inner"&gt;
    @others
          &lt;/div&gt;
</t>
<t tx="leo.20190426102506.194">           &lt;div class="sup-link"&gt;
    @others
           &lt;/div&gt;
</t>
<t tx="leo.20190426102506.195">            &lt;a class="left-link" href="#"&gt;
    @others
            &lt;/a&gt;
</t>
<t tx="leo.20190426102506.196">             &lt;i class="fa fa-link"&gt;
             &lt;/i&gt;
</t>
<t tx="leo.20190426102506.197">            &lt;a class="right-link" href="#"&gt;
    @others
            &lt;/a&gt;
</t>
<t tx="leo.20190426102506.198">             &lt;i class="fa fa-heart"&gt;
             &lt;/i&gt;
</t>
<t tx="leo.20190426102506.199">           &lt;div class="sup-meta-wrap"&gt;
    @others
           &lt;/div&gt;
</t>
<t tx="leo.20190426102506.2"> &lt;head&gt;
  &lt;!-- Required meta tags --&gt;
  &lt;meta charset="utf-8"/&gt;
  &lt;meta content="width=device-width, initial-scale=1, shrink-to-fit=no" name="viewport"/&gt;
    @others
 &lt;/head&gt;
</t>
<t tx="leo.20190426102506.20">        &lt;a class="nav-link" href="#services"&gt;
         Services
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.200">            &lt;a class="sup-title" href="#"&gt;
    @others
            &lt;/a&gt;
</t>
<t tx="leo.20190426102506.201">             &lt;h4&gt;
              TITLE HERE
             &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.202">            &lt;p class="sup-description"&gt;
             Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente vel quisquam.
            &lt;/p&gt;
</t>
<t tx="leo.20190426102506.203">      &lt;div class="col-lg-4 col-md-6 col-xs-12 mix branding research"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.204">       &lt;div class="portfolio-item"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.205">        &lt;div class="portfolio-img"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.206">         &lt;img alt="" src="img/portfolio/img3.jpg"&gt;
         &lt;/img&gt;
</t>
<t tx="leo.20190426102506.207">        &lt;div class="portfoli-content"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.208">         &lt;div class="sup-desc-wrap"&gt;
    @others
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.209">          &lt;div class="sup-desc-inner"&gt;
    @others
          &lt;/div&gt;
</t>
<t tx="leo.20190426102506.21">       &lt;li class="nav-item"&gt;
    @others
       &lt;/li&gt;
</t>
<t tx="leo.20190426102506.210">           &lt;div class="sup-link"&gt;
    @others
           &lt;/div&gt;
</t>
<t tx="leo.20190426102506.211">            &lt;a class="left-link" href="#"&gt;
    @others
            &lt;/a&gt;
</t>
<t tx="leo.20190426102506.212">             &lt;i class="fa fa-link"&gt;
             &lt;/i&gt;
</t>
<t tx="leo.20190426102506.213">            &lt;a class="right-link" href="#"&gt;
    @others
            &lt;/a&gt;
</t>
<t tx="leo.20190426102506.214">             &lt;i class="fa fa-heart"&gt;
             &lt;/i&gt;
</t>
<t tx="leo.20190426102506.215">           &lt;div class="sup-meta-wrap"&gt;
    @others
           &lt;/div&gt;
</t>
<t tx="leo.20190426102506.216">            &lt;a class="sup-title" href="#"&gt;
    @others
            &lt;/a&gt;
</t>
<t tx="leo.20190426102506.217">             &lt;h4&gt;
              TITLE HERE
             &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.218">            &lt;p class="sup-description"&gt;
             Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente vel quisquam.
            &lt;/p&gt;
</t>
<t tx="leo.20190426102506.219">      &lt;div class="col-lg-4 col-md-6 col-xs-12 mix marketing research"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.22">        &lt;a class="nav-link" href="#portfolio"&gt;
         Portfolio
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.220">       &lt;div class="portfolio-item"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.221">        &lt;div class="portfolio-img"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.222">         &lt;img alt="" src="img/portfolio/img4.jpg"&gt;
         &lt;/img&gt;
</t>
<t tx="leo.20190426102506.223">        &lt;div class="portfoli-content"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.224">         &lt;div class="sup-desc-wrap"&gt;
    @others
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.225">          &lt;div class="sup-desc-inner"&gt;
    @others
          &lt;/div&gt;
</t>
<t tx="leo.20190426102506.226">           &lt;div class="sup-link"&gt;
    @others
           &lt;/div&gt;
</t>
<t tx="leo.20190426102506.227">            &lt;a class="left-link" href="#"&gt;
    @others
            &lt;/a&gt;
</t>
<t tx="leo.20190426102506.228">             &lt;i class="fa fa-link"&gt;
             &lt;/i&gt;
</t>
<t tx="leo.20190426102506.229">            &lt;a class="right-link" href="#"&gt;
    @others
            &lt;/a&gt;
</t>
<t tx="leo.20190426102506.23">       &lt;li class="nav-item"&gt;
    @others
       &lt;/li&gt;
</t>
<t tx="leo.20190426102506.230">             &lt;i class="fa fa-heart"&gt;
             &lt;/i&gt;
</t>
<t tx="leo.20190426102506.231">           &lt;div class="sup-meta-wrap"&gt;
    @others
           &lt;/div&gt;
</t>
<t tx="leo.20190426102506.232">            &lt;a class="sup-title" href="#"&gt;
    @others
            &lt;/a&gt;
</t>
<t tx="leo.20190426102506.233">             &lt;h4&gt;
              TITLE HERE
             &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.234">            &lt;p class="sup-description"&gt;
             Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente vel quisquam.
            &lt;/p&gt;
</t>
<t tx="leo.20190426102506.235">      &lt;div class="col-lg-4 col-md-6 col-xs-12 mix marketing planning"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.236">       &lt;div class="portfolio-item"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.237">        &lt;div class="portfolio-img"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.238">         &lt;img alt="" src="img/portfolio/img5.jpg"&gt;
         &lt;/img&gt;
</t>
<t tx="leo.20190426102506.239">        &lt;div class="portfoli-content"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.24">        &lt;a class="nav-link" href="#feature"&gt;
         Features
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.240">         &lt;div class="sup-desc-wrap"&gt;
    @others
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.241">          &lt;div class="sup-desc-inner"&gt;
    @others
          &lt;/div&gt;
</t>
<t tx="leo.20190426102506.242">           &lt;div class="sup-link"&gt;
    @others
           &lt;/div&gt;
</t>
<t tx="leo.20190426102506.243">            &lt;a class="left-link" href="#"&gt;
    @others
            &lt;/a&gt;
</t>
<t tx="leo.20190426102506.244">             &lt;i class="fa fa-link"&gt;
             &lt;/i&gt;
</t>
<t tx="leo.20190426102506.245">            &lt;a class="right-link" href="#"&gt;
    @others
            &lt;/a&gt;
</t>
<t tx="leo.20190426102506.246">             &lt;i class="fa fa-heart"&gt;
             &lt;/i&gt;
</t>
<t tx="leo.20190426102506.247">           &lt;div class="sup-meta-wrap"&gt;
    @others
           &lt;/div&gt;
</t>
<t tx="leo.20190426102506.248">            &lt;a class="sup-title" href="#"&gt;
    @others
            &lt;/a&gt;
</t>
<t tx="leo.20190426102506.249">             &lt;h4&gt;
              TITLE HERE
             &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.25">       &lt;li class="nav-item"&gt;
    @others
       &lt;/li&gt;
</t>
<t tx="leo.20190426102506.250">            &lt;p class="sup-description"&gt;
             Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente vel quisquam.
            &lt;/p&gt;
</t>
<t tx="leo.20190426102506.251">      &lt;div class="col-lg-4 col-md-6 col-xs-12 mix planning research"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.252">       &lt;div class="portfolio-item"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.253">        &lt;div class="portfolio-img"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.254">         &lt;img alt="" src="img/portfolio/img6.jpg"&gt;
         &lt;/img&gt;
</t>
<t tx="leo.20190426102506.255">        &lt;div class="portfoli-content"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.256">         &lt;div class="sup-desc-wrap"&gt;
    @others
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.257">          &lt;div class="sup-desc-inner"&gt;
    @others
          &lt;/div&gt;
</t>
<t tx="leo.20190426102506.258">           &lt;div class="sup-link"&gt;
    @others
           &lt;/div&gt;
</t>
<t tx="leo.20190426102506.259">            &lt;a class="left-link" href="#"&gt;
    @others
            &lt;/a&gt;
</t>
<t tx="leo.20190426102506.26">        &lt;a class="nav-link" href="#team"&gt;
         Team
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.260">             &lt;i class="fa fa-link"&gt;
             &lt;/i&gt;
</t>
<t tx="leo.20190426102506.261">            &lt;a class="right-link" href="#"&gt;
    @others
            &lt;/a&gt;
</t>
<t tx="leo.20190426102506.262">             &lt;i class="fa fa-heart"&gt;
             &lt;/i&gt;
</t>
<t tx="leo.20190426102506.263">           &lt;div class="sup-meta-wrap"&gt;
    @others
           &lt;/div&gt;
</t>
<t tx="leo.20190426102506.264">            &lt;a class="sup-title" href="#"&gt;
    @others
            &lt;/a&gt;
</t>
<t tx="leo.20190426102506.265">             &lt;h4&gt;
              TITLE HERE
             &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.266">            &lt;p class="sup-description"&gt;
             Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente vel quisquam.
            &lt;/p&gt;
</t>
<t tx="leo.20190426102506.267">  &lt;div class="section-padding" id="feature"&gt;
    @others
  &lt;/div&gt;
  &lt;!-- Feature Section End --&gt;
  &lt;!-- facts Section Start --&gt;
</t>
<t tx="leo.20190426102506.268">   &lt;div class="container"&gt;
    @others
   &lt;/div&gt;
</t>
<t tx="leo.20190426102506.269">    &lt;div class="row"&gt;
    @others
    &lt;/div&gt;
</t>
<t tx="leo.20190426102506.27">       &lt;li class="nav-item"&gt;
    @others
       &lt;/li&gt;
</t>
<t tx="leo.20190426102506.270">     &lt;div class="col-md-12"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.271">      &lt;h2 class="section-title wow fadeInDown animated" data-wow-delay="0.3s"&gt;
       Features
      &lt;/h2&gt;
</t>
<t tx="leo.20190426102506.272">    &lt;div class="row"&gt;
     &lt;!-- Start featured --&gt;
    @others
    &lt;/div&gt;
</t>
<t tx="leo.20190426102506.273">     &lt;div class="col-lg-4 col-md-6 col-xs-12"&gt;
    @others
     &lt;/div&gt;
     &lt;!-- End featured --&gt;
     &lt;!-- Start featured --&gt;
</t>
<t tx="leo.20190426102506.274">      &lt;div class="featured-box-item"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.275">       &lt;div class="featured-icon"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.276">        &lt;i class="fa fa-bolt"&gt;
        &lt;/i&gt;
</t>
<t tx="leo.20190426102506.277">       &lt;div class="featured-content"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.278">        &lt;h4&gt;
         Bootstrap 4
        &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.279">        &lt;p&gt;
         Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et magna aliqua.
        &lt;/p&gt;
</t>
<t tx="leo.20190426102506.28">        &lt;a class="nav-link" href="#pricing"&gt;
         Pricing
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.280">     &lt;div class="col-lg-4 col-md-6 col-xs-12"&gt;
    @others
     &lt;/div&gt;
     &lt;!-- End featured --&gt;
     &lt;!-- Start featured --&gt;
</t>
<t tx="leo.20190426102506.281">      &lt;div class="featured-box-item"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.282">       &lt;div class="featured-icon"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.283">        &lt;i class="fa fa-diamond"&gt;
        &lt;/i&gt;
</t>
<t tx="leo.20190426102506.284">       &lt;div class="featured-content"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.285">        &lt;h4&gt;
         Clean Design
        &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.286">        &lt;p&gt;
         Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et magna aliqua.
        &lt;/p&gt;
</t>
<t tx="leo.20190426102506.287">     &lt;div class="col-lg-4 col-md-6 col-xs-12"&gt;
    @others
     &lt;/div&gt;
     &lt;!-- End featured --&gt;
     &lt;!-- Start featured --&gt;
</t>
<t tx="leo.20190426102506.288">      &lt;div class="featured-box-item"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.289">       &lt;div class="featured-icon"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.29">       &lt;li class="nav-item"&gt;
    @others
       &lt;/li&gt;
</t>
<t tx="leo.20190426102506.290">        &lt;i class="fa fa-cubes"&gt;
        &lt;/i&gt;
</t>
<t tx="leo.20190426102506.291">       &lt;div class="featured-content"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.292">        &lt;h4&gt;
         100+ Components
        &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.293">        &lt;p&gt;
         Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et magna aliqua.
        &lt;/p&gt;
</t>
<t tx="leo.20190426102506.294">     &lt;div class="col-lg-4 col-md-6 col-xs-12"&gt;
    @others
     &lt;/div&gt;
     &lt;!-- End featured --&gt;
     &lt;!-- Start featured --&gt;
</t>
<t tx="leo.20190426102506.295">      &lt;div class="featured-box-item"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.296">       &lt;div class="featured-icon"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.297">        &lt;i class="fa fa-cogs"&gt;
        &lt;/i&gt;
</t>
<t tx="leo.20190426102506.298">       &lt;div class="featured-content"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.299">        &lt;h4&gt;
         Easy to Customize
        &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.3">  &lt;title&gt;
   Helium - Bootstrap 4 Onepage Template
  &lt;/title&gt;
  &lt;!-- Bootstrap CSS --&gt;
  &lt;link href="css/bootstrap.min.css" rel="stylesheet" type="text/css"/&gt;
  &lt;!-- Font --&gt;
  &lt;link href="css/font-awesome.min.css" rel="stylesheet" type="text/css"/&gt;
  &lt;!-- Slicknav --&gt;
  &lt;link href="css/slicknav.css" rel="stylesheet" type="text/css"/&gt;
  &lt;!-- Owl carousel --&gt;
  &lt;link href="css/owl.carousel.css" rel="stylesheet" type="text/css"/&gt;
  &lt;link href="css/owl.theme.css" rel="stylesheet" type="text/css"/&gt;
  &lt;!-- Animate --&gt;
  &lt;link href="css/animate.css" rel="stylesheet" type="text/css"/&gt;
  &lt;!-- Main Style --&gt;
  &lt;link href="css/main.css" rel="stylesheet" type="text/css"/&gt;
  &lt;!-- Extras Style --&gt;
  &lt;link href="css/extras.css" rel="stylesheet" type="text/css"/&gt;
  &lt;!-- Responsive Style --&gt;
  &lt;link href="css/responsive.css" rel="stylesheet" type="text/css"/&gt;
</t>
<t tx="leo.20190426102506.30">        &lt;a class="nav-link" href="#contact"&gt;
         Contact
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.300">        &lt;p&gt;
         Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et magna aliqua.
        &lt;/p&gt;
</t>
<t tx="leo.20190426102506.301">     &lt;div class="col-lg-4 col-md-6 col-xs-12"&gt;
    @others
     &lt;/div&gt;
     &lt;!-- End featured --&gt;
     &lt;!-- Start featured --&gt;
</t>
<t tx="leo.20190426102506.302">      &lt;div class="featured-box-item"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.303">       &lt;div class="featured-icon"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.304">        &lt;i class="fa fa-check"&gt;
        &lt;/i&gt;
</t>
<t tx="leo.20190426102506.305">       &lt;div class="featured-content"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.306">        &lt;h4&gt;
         Pixel Perfect
        &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.307">        &lt;p&gt;
         Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et magna aliqua.
        &lt;/p&gt;
</t>
<t tx="leo.20190426102506.308">     &lt;div class="col-lg-4 col-md-6 col-xs-12"&gt;
    @others
     &lt;/div&gt;
     &lt;!-- End featured --&gt;
</t>
<t tx="leo.20190426102506.309">      &lt;div class="featured-box-item"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.31">    &lt;ul class="mobile-menu navbar-nav"&gt;
    @others
    &lt;/ul&gt;
    &lt;!-- Mobile Menu End --&gt;
   &lt;/nav&gt;
   &lt;!-- Navbar End --&gt;
   &lt;!-- sliders --&gt;
</t>
<t tx="leo.20190426102506.310">       &lt;div class="featured-icon"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.311">        &lt;i class="fa fa-cloud"&gt;
        &lt;/i&gt;
</t>
<t tx="leo.20190426102506.312">       &lt;div class="featured-content"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.313">        &lt;h4&gt;
         Cloud Backup
        &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.314">        &lt;p&gt;
         Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et magna aliqua.
        &lt;/p&gt;
</t>
<t tx="leo.20190426102506.315">  &lt;div id="counter"&gt;
    @others
  &lt;/div&gt;
  &lt;!-- facts Section End --&gt;
  &lt;!-- Team Section Start --&gt;
</t>
<t tx="leo.20190426102506.316">   &lt;div class="container"&gt;
    @others
   &lt;/div&gt;
</t>
<t tx="leo.20190426102506.317">    &lt;div class="row count-to-sec"&gt;
    @others
    &lt;/div&gt;
</t>
<t tx="leo.20190426102506.318">     &lt;div class="col-lg-3 col-md-6 col-xs-12 count-one"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.319">      &lt;span class="icon"&gt;
    @others
      &lt;/span&gt;
</t>
<t tx="leo.20190426102506.32">     &lt;li&gt;
    @others
     &lt;/li&gt;
</t>
<t tx="leo.20190426102506.320">       &lt;i class="fa fa-download"&gt;
       &lt;/i&gt;
</t>
<t tx="leo.20190426102506.321">      &lt;h3 class="timer count-value" data-speed="1000" data-to="561"&gt;
       561
      &lt;/h3&gt;
      &lt;hr class="width25-divider"/&gt;
</t>
<t tx="leo.20190426102506.322">      &lt;small class="count-title"&gt;
       Downloads
      &lt;/small&gt;
</t>
<t tx="leo.20190426102506.323">     &lt;div class="col-lg-3 col-md-6 col-xs-12 count-one"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.324">      &lt;span class="icon"&gt;
    @others
      &lt;/span&gt;
</t>
<t tx="leo.20190426102506.325">       &lt;i class="fa fa-user"&gt;
       &lt;/i&gt;
</t>
<t tx="leo.20190426102506.326">      &lt;h3 class="timer count-value" data-speed="1000" data-to="950"&gt;
       950
      &lt;/h3&gt;
      &lt;hr class="width25-divider"/&gt;
</t>
<t tx="leo.20190426102506.327">      &lt;small class="count-title"&gt;
       Developers
      &lt;/small&gt;
</t>
<t tx="leo.20190426102506.328">     &lt;div class="col-lg-3 col-md-6 col-xs-12 count-one"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.329">      &lt;span class="icon"&gt;
    @others
      &lt;/span&gt;
</t>
<t tx="leo.20190426102506.33">      &lt;a class="page-scroll" href="#sliders"&gt;
       Home
      &lt;/a&gt;
</t>
<t tx="leo.20190426102506.330">       &lt;i class="fa fa-desktop"&gt;
       &lt;/i&gt;
</t>
<t tx="leo.20190426102506.331">      &lt;h3 class="timer count-value" data-speed="1000" data-to="978"&gt;
       978
      &lt;/h3&gt;
      &lt;hr class="width25-divider"/&gt;
</t>
<t tx="leo.20190426102506.332">      &lt;small class="count-title"&gt;
       Lines of code written
      &lt;/small&gt;
</t>
<t tx="leo.20190426102506.333">     &lt;div class="col-lg-3 col-md-6 col-xs-12 count-one"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.334">      &lt;span class="icon"&gt;
    @others
      &lt;/span&gt;
</t>
<t tx="leo.20190426102506.335">       &lt;i class="fa fa-coffee"&gt;
       &lt;/i&gt;
</t>
<t tx="leo.20190426102506.336">      &lt;h3 class="timer count-value" data-speed="1000" data-to="1700"&gt;
       1700
      &lt;/h3&gt;
      &lt;hr class="width25-divider"/&gt;
</t>
<t tx="leo.20190426102506.337">      &lt;small class="count-title"&gt;
       Cups of coffee consumed
      &lt;/small&gt;
</t>
<t tx="leo.20190426102506.338">  &lt;div class="team-members-tow section-padding" id="team"&gt;
    @others
  &lt;/div&gt;
  &lt;!-- Team Section End --&gt;
  &lt;!-- Pricing section Start --&gt;
  &lt;section class="section-padding" id="pricing"&gt;
</t>
<t tx="leo.20190426102506.339">   &lt;div class="container"&gt;
    @others
   &lt;/div&gt;
</t>
<t tx="leo.20190426102506.34">     &lt;li&gt;
    @others
     &lt;/li&gt;
</t>
<t tx="leo.20190426102506.340">    &lt;div class="row"&gt;
    @others
    &lt;/div&gt;
</t>
<t tx="leo.20190426102506.341">     &lt;div class="col-md-12"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.342">      &lt;h2 class="section-title wow fadeInDown animated" data-wow-delay="0.3s"&gt;
       Our Team
      &lt;/h2&gt;
</t>
<t tx="leo.20190426102506.343">    &lt;div class="row"&gt;
    @others
    &lt;/div&gt;
</t>
<t tx="leo.20190426102506.344">     &lt;div class="col-lg-4 col-md-6 col-xs-12"&gt;
      &lt;!-- Team Item Starts --&gt;
      &lt;figure&gt;
       &lt;img alt="" src="img/team/team-05.jpg"/&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.345">       &lt;div class="image-overlay"&gt;
    @others
       &lt;/div&gt;
      &lt;/figure&gt;
      &lt;!-- Team Item Ends --&gt;
</t>
<t tx="leo.20190426102506.346">        &lt;div class="overlay-text text-center"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.347">         &lt;div class="info-text"&gt;
    @others
         &lt;/div&gt;
         &lt;hr class="small-divider"/&gt;
</t>
<t tx="leo.20190426102506.348">          &lt;strong&gt;
           Melody Clark
          &lt;/strong&gt;
</t>
<t tx="leo.20190426102506.349">          &lt;span&gt;
           UX Specialist
          &lt;/span&gt;
</t>
<t tx="leo.20190426102506.35">      &lt;a class="page-scroll" href="#about"&gt;
       About
      &lt;/a&gt;
</t>
<t tx="leo.20190426102506.350">         &lt;ul class="social-icons"&gt;
    @others
         &lt;/ul&gt;
</t>
<t tx="leo.20190426102506.351">          &lt;li&gt;
    @others
          &lt;/li&gt;
</t>
<t tx="leo.20190426102506.352">           &lt;a href="#"&gt;
    @others
           &lt;/a&gt;
</t>
<t tx="leo.20190426102506.353">            &lt;i aria-hidden="true" class="fa fa-facebook"&gt;
            &lt;/i&gt;
</t>
<t tx="leo.20190426102506.354">          &lt;li&gt;
    @others
          &lt;/li&gt;
</t>
<t tx="leo.20190426102506.355">           &lt;a href="#"&gt;
    @others
           &lt;/a&gt;
</t>
<t tx="leo.20190426102506.356">            &lt;i aria-hidden="true" class="fa fa-twitter"&gt;
            &lt;/i&gt;
</t>
<t tx="leo.20190426102506.357">          &lt;li&gt;
    @others
          &lt;/li&gt;
</t>
<t tx="leo.20190426102506.358">           &lt;a href="#"&gt;
    @others
           &lt;/a&gt;
</t>
<t tx="leo.20190426102506.359">            &lt;i aria-hidden="true" class="fa fa-instagram"&gt;
            &lt;/i&gt;
</t>
<t tx="leo.20190426102506.36">     &lt;li&gt;
    @others
     &lt;/li&gt;
</t>
<t tx="leo.20190426102506.360">     &lt;div class="col-lg-4 col-md-6 col-xs-12"&gt;
      &lt;!-- Team Item Starts --&gt;
      &lt;figure&gt;
       &lt;img alt="" src="img/team/team-06.jpg"/&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.361">       &lt;div class="image-overlay"&gt;
    @others
       &lt;/div&gt;
      &lt;/figure&gt;
      &lt;!-- Team Item Ends --&gt;
</t>
<t tx="leo.20190426102506.362">        &lt;div class="overlay-text text-center"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.363">         &lt;div class="info-text"&gt;
    @others
         &lt;/div&gt;
         &lt;hr class="small-divider"/&gt;
</t>
<t tx="leo.20190426102506.364">          &lt;strong&gt;
           Danny Burton
          &lt;/strong&gt;
</t>
<t tx="leo.20190426102506.365">          &lt;span&gt;
           Senior Designer
          &lt;/span&gt;
</t>
<t tx="leo.20190426102506.366">         &lt;ul class="social-icons"&gt;
    @others
         &lt;/ul&gt;
</t>
<t tx="leo.20190426102506.367">          &lt;li&gt;
    @others
          &lt;/li&gt;
</t>
<t tx="leo.20190426102506.368">           &lt;a href="#"&gt;
    @others
           &lt;/a&gt;
</t>
<t tx="leo.20190426102506.369">            &lt;i aria-hidden="true" class="fa fa-facebook"&gt;
            &lt;/i&gt;
</t>
<t tx="leo.20190426102506.37">      &lt;a class="page-scroll" href="#services"&gt;
       Services
      &lt;/a&gt;
</t>
<t tx="leo.20190426102506.370">          &lt;li&gt;
    @others
          &lt;/li&gt;
</t>
<t tx="leo.20190426102506.371">           &lt;a href="#"&gt;
    @others
           &lt;/a&gt;
</t>
<t tx="leo.20190426102506.372">            &lt;i aria-hidden="true" class="fa fa-twitter"&gt;
            &lt;/i&gt;
</t>
<t tx="leo.20190426102506.373">          &lt;li&gt;
    @others
          &lt;/li&gt;
</t>
<t tx="leo.20190426102506.374">           &lt;a href="#"&gt;
    @others
           &lt;/a&gt;
</t>
<t tx="leo.20190426102506.375">            &lt;i aria-hidden="true" class="fa fa-instagram"&gt;
            &lt;/i&gt;
</t>
<t tx="leo.20190426102506.376">     &lt;div class="col-lg-4 col-md-6 col-xs-12"&gt;
      &lt;!-- Team Item Starts --&gt;
      &lt;figure&gt;
       &lt;img alt="" src="img/team/team-07.jpg"/&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.377">       &lt;div class="image-overlay"&gt;
    @others
       &lt;/div&gt;
      &lt;/figure&gt;
      &lt;!-- Team Item Ends --&gt;
</t>
<t tx="leo.20190426102506.378">        &lt;div class="overlay-text text-center"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.379">         &lt;div class="info-text"&gt;
    @others
         &lt;/div&gt;
         &lt;hr class="small-divider"/&gt;
</t>
<t tx="leo.20190426102506.38">     &lt;li&gt;
    @others
     &lt;/li&gt;
</t>
<t tx="leo.20190426102506.380">          &lt;strong&gt;
           Elizabeth Jones
          &lt;/strong&gt;
</t>
<t tx="leo.20190426102506.381">          &lt;span&gt;
           Art Director
          &lt;/span&gt;
</t>
<t tx="leo.20190426102506.382">         &lt;ul class="social-icons"&gt;
    @others
         &lt;/ul&gt;
</t>
<t tx="leo.20190426102506.383">          &lt;li&gt;
    @others
          &lt;/li&gt;
</t>
<t tx="leo.20190426102506.384">           &lt;a href="#"&gt;
    @others
           &lt;/a&gt;
</t>
<t tx="leo.20190426102506.385">            &lt;i aria-hidden="true" class="fa fa-facebook"&gt;
            &lt;/i&gt;
</t>
<t tx="leo.20190426102506.386">          &lt;li&gt;
    @others
          &lt;/li&gt;
</t>
<t tx="leo.20190426102506.387">           &lt;a href="#"&gt;
    @others
           &lt;/a&gt;
</t>
<t tx="leo.20190426102506.388">            &lt;i aria-hidden="true" class="fa fa-twitter"&gt;
            &lt;/i&gt;
</t>
<t tx="leo.20190426102506.389">          &lt;li&gt;
    @others
          &lt;/li&gt;
</t>
<t tx="leo.20190426102506.39">      &lt;a class="page-scroll" href="#portfolio"&gt;
       Portfolio
      &lt;/a&gt;
</t>
<t tx="leo.20190426102506.390">           &lt;a href="#"&gt;
    @others
           &lt;/a&gt;
</t>
<t tx="leo.20190426102506.391">            &lt;i aria-hidden="true" class="fa fa-instagram"&gt;
            &lt;/i&gt;
</t>
<t tx="leo.20190426102506.392">   &lt;div class="container"&gt;
    @others
   &lt;/div&gt;
  &lt;/section&gt;
  &lt;!-- Pricing Table Section End --&gt;
  &lt;!-- Single testimonial Start --&gt;
</t>
<t tx="leo.20190426102506.393">    &lt;div class="row"&gt;
    @others
    &lt;/div&gt;
</t>
<t tx="leo.20190426102506.394">     &lt;div class="col-md-12"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.395">      &lt;h2 class="section-title wow fadeInDown animated" data-wow-delay="0.3s"&gt;
       Pricing Table
      &lt;/h2&gt;
</t>
<t tx="leo.20190426102506.396">    &lt;div class="row"&gt;
    @others
    &lt;/div&gt;
</t>
<t tx="leo.20190426102506.397">     &lt;div class="col-lg-4 col-md-6 col-xs-12"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.398">      &lt;div class="pricing-table-item"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.399">       &lt;div class="plan-name"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.4"> &lt;body&gt;
  &lt;!-- Header Area wrapper Starts --&gt;
  &lt;header id="header-wrap"&gt;
   &lt;!-- Navbar Start --&gt;
   &lt;nav class="navbar navbar-expand-lg fixed-top scrolling-navbar indigo"&gt;
    @others
 &lt;/body&gt;
</t>
<t tx="leo.20190426102506.40">     &lt;li&gt;
    @others
     &lt;/li&gt;
</t>
<t tx="leo.20190426102506.400">        &lt;h3&gt;
         Basic
        &lt;/h3&gt;
</t>
<t tx="leo.20190426102506.401">       &lt;div class="plan-price"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.402">        &lt;div class="price-value"&gt;
         $ 10
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.403">        &lt;div class="interval"&gt;
         per month
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.404">       &lt;div class="plan-list"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.405">        &lt;ul&gt;
    @others
        &lt;/ul&gt;
</t>
<t tx="leo.20190426102506.406">         &lt;li&gt;
    @others
         &lt;/li&gt;
</t>
<t tx="leo.20190426102506.407">          &lt;i class="fa fa-check"&gt;
          &lt;/i&gt;
          2GB Disk Space
</t>
<t tx="leo.20190426102506.408">         &lt;li&gt;
    @others
         &lt;/li&gt;
</t>
<t tx="leo.20190426102506.409">          &lt;i class="fa fa-check"&gt;
          &lt;/i&gt;
          3 Sub Domains
</t>
<t tx="leo.20190426102506.41">      &lt;a class="page-scroll" href="#feature"&gt;
       Features
      &lt;/a&gt;
</t>
<t tx="leo.20190426102506.410">         &lt;li&gt;
    @others
         &lt;/li&gt;
</t>
<t tx="leo.20190426102506.411">          &lt;i class="fa fa-check"&gt;
          &lt;/i&gt;
          12 Database
</t>
<t tx="leo.20190426102506.412">         &lt;li&gt;
    @others
         &lt;/li&gt;
</t>
<t tx="leo.20190426102506.413">          &lt;i class="fa fa-check"&gt;
          &lt;/i&gt;
          Unlimited Users
</t>
<t tx="leo.20190426102506.414">       &lt;div class="plan-signup"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.415">        &lt;a class="btn btn-common" href="#"&gt;
         Get Started
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.416">     &lt;div class="col-lg-4 col-md-6 col-xs-12"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.417">      &lt;div class="pricing-table-item table-active"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.418">       &lt;div class="plan-name"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.419">        &lt;h3&gt;
         Premium
        &lt;/h3&gt;
</t>
<t tx="leo.20190426102506.42">     &lt;li&gt;
    @others
     &lt;/li&gt;
</t>
<t tx="leo.20190426102506.420">       &lt;div class="plan-price"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.421">        &lt;div class="price-value"&gt;
         $ 69
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.422">        &lt;div class="interval"&gt;
         per month
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.423">       &lt;div class="plan-list"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.424">        &lt;ul&gt;
    @others
        &lt;/ul&gt;
</t>
<t tx="leo.20190426102506.425">         &lt;li&gt;
    @others
         &lt;/li&gt;
</t>
<t tx="leo.20190426102506.426">          &lt;i class="fa fa-check"&gt;
          &lt;/i&gt;
          10GB Disk Space
</t>
<t tx="leo.20190426102506.427">         &lt;li&gt;
    @others
         &lt;/li&gt;
</t>
<t tx="leo.20190426102506.428">          &lt;i class="fa fa-check"&gt;
          &lt;/i&gt;
          5 Sub Domains
</t>
<t tx="leo.20190426102506.429">         &lt;li&gt;
    @others
         &lt;/li&gt;
</t>
<t tx="leo.20190426102506.43">      &lt;a class="page-scroll" href="#team"&gt;
       Team
      &lt;/a&gt;
</t>
<t tx="leo.20190426102506.430">          &lt;i class="fa fa-check"&gt;
          &lt;/i&gt;
          12 Database
</t>
<t tx="leo.20190426102506.431">         &lt;li&gt;
    @others
         &lt;/li&gt;
</t>
<t tx="leo.20190426102506.432">          &lt;i class="fa fa-check"&gt;
          &lt;/i&gt;
          Unlimited Users
</t>
<t tx="leo.20190426102506.433">       &lt;div class="plan-signup"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.434">        &lt;a class="btn btn-common" href="#"&gt;
         Get Started
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.435">     &lt;div class="col-lg-4 col-md-6 col-xs-12"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.436">      &lt;div class="pricing-table-item"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.437">       &lt;div class="plan-name"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.438">        &lt;h3&gt;
         Unltimate
        &lt;/h3&gt;
</t>
<t tx="leo.20190426102506.439">       &lt;div class="plan-price"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.44">     &lt;li&gt;
    @others
     &lt;/li&gt;
</t>
<t tx="leo.20190426102506.440">        &lt;div class="price-value"&gt;
         $ 79
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.441">        &lt;div class="interval"&gt;
         per month
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.442">       &lt;div class="plan-list"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.443">        &lt;ul&gt;
    @others
        &lt;/ul&gt;
</t>
<t tx="leo.20190426102506.444">         &lt;li&gt;
    @others
         &lt;/li&gt;
</t>
<t tx="leo.20190426102506.445">          &lt;i class="fa fa-check"&gt;
          &lt;/i&gt;
          50GB Disk Space
</t>
<t tx="leo.20190426102506.446">         &lt;li&gt;
    @others
         &lt;/li&gt;
</t>
<t tx="leo.20190426102506.447">          &lt;i class="fa fa-check"&gt;
          &lt;/i&gt;
          20 Sub Domains
</t>
<t tx="leo.20190426102506.448">         &lt;li&gt;
    @others
         &lt;/li&gt;
</t>
<t tx="leo.20190426102506.449">          &lt;i class="fa fa-check"&gt;
          &lt;/i&gt;
          36 Database
</t>
<t tx="leo.20190426102506.45">      &lt;a class="page-scroll" href="#pricing"&gt;
       Pricing
      &lt;/a&gt;
</t>
<t tx="leo.20190426102506.450">         &lt;li&gt;
    @others
         &lt;/li&gt;
</t>
<t tx="leo.20190426102506.451">          &lt;i class="fa fa-check"&gt;
          &lt;/i&gt;
          Unlimited Users
</t>
<t tx="leo.20190426102506.452">       &lt;div class="plan-signup"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.453">        &lt;a class="btn btn-common" href="#"&gt;
         Get Started
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.454">  &lt;div class="single-testimonial-area"&gt;
    @others
  &lt;/div&gt;
  &lt;!-- end --&gt;
  &lt;!-- Contact Form Section Start --&gt;
  &lt;section class="contact-form section-padding" id="contact"&gt;
</t>
<t tx="leo.20190426102506.455">   &lt;div class="container"&gt;
    @others
   &lt;/div&gt;
</t>
<t tx="leo.20190426102506.456">    &lt;div class="owl-carousel" id="single-testimonial-item"&gt;
     &lt;!-- Single testimonial Item --&gt;
    @others
    &lt;/div&gt;
</t>
<t tx="leo.20190426102506.457">     &lt;div class="item"&gt;
    @others
     &lt;/div&gt;
     &lt;!-- Single testimonial Item --&gt;
</t>
<t tx="leo.20190426102506.458">      &lt;div class="row justify-content-md-center"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.459">       &lt;div class="col-lg-8 col-md-12 col-xs-12 col-md-auto"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.46">     &lt;li&gt;
    @others
     &lt;/li&gt;
</t>
<t tx="leo.20190426102506.460">        &lt;div class="testimonial-inner text-md-center"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.461">         &lt;blockquote&gt;
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id ipsam, non ut molestiae rerum praesentium repellat debitis iure reiciendis, eius culpa beatae commodi facere ad numquam. Quisquam dignissimos similique sunt iure fugit, omnis vel cupiditate repellendus magni nihil molestiae quam, delectus
         &lt;/blockquote&gt;
</t>
<t tx="leo.20190426102506.462">         &lt;div class="testimonial-images"&gt;
          &lt;img alt="" class="img-circle text-md-center" src="img/testimonial/img1.jpg"/&gt;
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.463">         &lt;div class="testimonial-footer"&gt;
    @others
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.464">          &lt;i class="fa fa-user"&gt;
          &lt;/i&gt;
          Arman
</t>
<t tx="leo.20190426102506.465">          &lt;a href="#"&gt;
           UIdeck
          &lt;/a&gt;
</t>
<t tx="leo.20190426102506.466">     &lt;div class="item"&gt;
    @others
     &lt;/div&gt;
     &lt;!-- Single testimonial Item --&gt;
</t>
<t tx="leo.20190426102506.467">      &lt;div class="row justify-content-md-center"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.468">       &lt;div class="col-lg-8 col-md-12 col-xs-12 col-md-auto"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.469">        &lt;div class="testimonial-inner text-md-center"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.47">      &lt;a class="page-scroll" href="#contact"&gt;
       Contact
      &lt;/a&gt;
</t>
<t tx="leo.20190426102506.470">         &lt;blockquote&gt;
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id ipsam, non ut molestiae rerum praesentium repellat debitis iure reiciendis, eius culpa beatae commodi facere ad numquam. Quisquam dignissimos similique sunt iure fugit, omnis vel cupiditate repellendus magni nihil molestiae quam, delectus
         &lt;/blockquote&gt;
</t>
<t tx="leo.20190426102506.471">         &lt;div class="testimonial-images"&gt;
          &lt;img alt="" class="img-circle text-md-center" src="img/testimonial/img2.jpg"/&gt;
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.472">         &lt;div class="testimonial-footer"&gt;
    @others
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.473">          &lt;i class="fa fa-user"&gt;
          &lt;/i&gt;
          Jeniffer
</t>
<t tx="leo.20190426102506.474">          &lt;a href="#"&gt;
           GrayGrids
          &lt;/a&gt;
</t>
<t tx="leo.20190426102506.475">     &lt;div class="item"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.476">      &lt;div class="row justify-content-md-center"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.477">       &lt;div class="col-lg-8 col-md-12 col-xs-12 col-md-auto"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.478">        &lt;div class="testimonial-inner text-md-center"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.479">         &lt;blockquote&gt;
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id ipsam, non ut molestiae rerum praesentium repellat debitis iure reiciendis, eius culpa beatae commodi facere ad numquam. Quisquam dignissimos similique sunt iure fugit, omnis vel cupiditate repellendus magni nihil molestiae quam, delectus
         &lt;/blockquote&gt;
</t>
<t tx="leo.20190426102506.48">   &lt;div id="sliders"&gt;
    @others
   &lt;/div&gt;
   &lt;!-- End sliders --&gt;
  &lt;/header&gt;
  &lt;!-- Header Area wrapper End --&gt;
  &lt;!-- About Section Start --&gt;
</t>
<t tx="leo.20190426102506.480">         &lt;div class="testimonial-images"&gt;
          &lt;img alt="" class="img-circle text-md-center" src="img/testimonial/img3.jpg"/&gt;
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.481">         &lt;div class="testimonial-footer"&gt;
    @others
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.482">          &lt;i class="fa fa-user"&gt;
          &lt;/i&gt;
          Elon Musk
</t>
<t tx="leo.20190426102506.483">          &lt;a href="#"&gt;
           Tesla
          &lt;/a&gt;
</t>
<t tx="leo.20190426102506.484">   &lt;div class="container"&gt;
    @others
   &lt;/div&gt;
  &lt;/section&gt;
  &lt;!-- Contact Form Section End --&gt;
  &lt;!-- Footer Section --&gt;
  &lt;footer class="footer"&gt;
   &lt;!-- Container Starts --&gt;
</t>
<t tx="leo.20190426102506.485">    &lt;div class="row"&gt;
    @others
    &lt;/div&gt;
</t>
<t tx="leo.20190426102506.486">     &lt;div class="col-md-12"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.487">      &lt;h2 class="section-title wow fadeInDown animated" data-wow-delay="0.3s"&gt;
       Contact Us
      &lt;/h2&gt;
</t>
<t tx="leo.20190426102506.488">    &lt;div class="row"&gt;
    @others
    &lt;/div&gt;
</t>
<t tx="leo.20190426102506.489">     &lt;div class="col-lg-8 col-md-6 col-xs-12"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.49">    &lt;div class="full-width"&gt;
     &lt;!-- light slider --&gt;
    @others
    &lt;/div&gt;
</t>
<t tx="leo.20190426102506.490">      &lt;h3 class="title-head text-left"&gt;
       Get in touch
      &lt;/h3&gt;
</t>
<t tx="leo.20190426102506.491">      &lt;form class="contact-form" data-toggle="validator"&gt;
    @others
      &lt;/form&gt;
</t>
<t tx="leo.20190426102506.492">       &lt;div class="row"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.493">        &lt;div class="col-lg-4 col-md-12 col-xs-12"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.494">         &lt;div class="form-group"&gt;
    @others
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.495">          &lt;i class="contact-icon fa fa-user"&gt;
          &lt;/i&gt;
          &lt;input class="form-control" data-error="Please enter your name" id="name" placeholder="Full Name" required="" type="text"/&gt;
</t>
<t tx="leo.20190426102506.496">          &lt;div class="help-block with-errors"&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20190426102506.497">        &lt;div class="col-lg-4 col-md-12 col-xs-12"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.498">         &lt;div class="form-group"&gt;
    @others
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.499">          &lt;i class="contact-icon fa fa-envelope-o"&gt;
          &lt;/i&gt;
          &lt;input class="form-control" data-error="Please enter your email" id="email" placeholder="Email" required="" type="email"/&gt;
</t>
<t tx="leo.20190426102506.5">    &lt;div class="container"&gt;
     &lt;!-- Brand and toggle get grouped for better mobile display --&gt;
    @others
    &lt;/div&gt;
    &lt;!-- Mobile Menu Start --&gt;
</t>
<t tx="leo.20190426102506.50">     &lt;div class="carousel slide" id="light-slider"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.500">          &lt;div class="help-block with-errors"&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20190426102506.501">        &lt;div class="col-lg-4 col-md-12 col-xs-12"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.502">         &lt;div class="form-group"&gt;
    @others
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.503">          &lt;i class="contact-icon fa fa-pencil-square-o"&gt;
          &lt;/i&gt;
          &lt;input class="form-control" data-error="Please enter your Subject" id="subject" placeholder="Subject" required="" type="text"/&gt;
</t>
<t tx="leo.20190426102506.504">          &lt;div class="help-block with-errors"&gt;
          &lt;/div&gt;
</t>
<t tx="leo.20190426102506.505">        &lt;div class="col-lg-12 col-md-12 col-xs-12"&gt;
         &lt;textarea class="form-control" data-error="Please enter your message" id="message" placeholder="Message" required="" rows="4"&gt;&lt;/textarea&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.506">         &lt;div class="help-block with-errors"&gt;
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.507">         &lt;button class="btn btn-common btn-form-submit" id="form-submit" type="submit"&gt;
          Send Message
         &lt;/button&gt;
</t>
<t tx="leo.20190426102506.508">         &lt;div class="h3 text-center hidden" id="msgSubmit"&gt;
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.509">         &lt;div class="clearfix"&gt;
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.51">      &lt;div id="carousel-area"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.510">     &lt;div class="col-lg-4 col-md-6 col-xs-12"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.511">      &lt;h4 class="contact-info-title text-left"&gt;
       Contact Information
      &lt;/h4&gt;
</t>
<t tx="leo.20190426102506.512">      &lt;div class="contact-info"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.513">       &lt;address&gt;
    @others
       &lt;/address&gt;
</t>
<t tx="leo.20190426102506.514">        &lt;i class="lni-map-marker icons cyan-color contact-info-icon"&gt;
        &lt;/i&gt;
        Level 13, 2 Elizabeth St, Melbourne,
</t>
<t tx="leo.20190426102506.515">       &lt;div class="tel-info"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.516">        &lt;a href="tel:1800452308"&gt;
    @others
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.517">         &lt;i class="lni-mobile icons cyan-color contact-info-icon"&gt;
         &lt;/i&gt;
         1800 452 308
</t>
<t tx="leo.20190426102506.518">        &lt;a href="tel:+61(8)82343555"&gt;
    @others
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.519">         &lt;i class="lni-phone icons cyan-color contact-info-icon"&gt;
         &lt;/i&gt;
         +61 (8) 8234 3555
</t>
<t tx="leo.20190426102506.52">       &lt;div class="carousel slide" data-ride="carousel" id="carousel-slider"&gt;
    @others
       &lt;/div&gt;
</t>
<t tx="leo.20190426102506.520">       &lt;a href="mailto:hello@spiritapp.com"&gt;
    @others
       &lt;/a&gt;
</t>
<t tx="leo.20190426102506.521">        &lt;i class="lni-envelope icons cyan-color contact-info-icon"&gt;
        &lt;/i&gt;
        admin@uideck.com
</t>
<t tx="leo.20190426102506.522">       &lt;a href="#"&gt;
    @others
       &lt;/a&gt;
</t>
<t tx="leo.20190426102506.523">        &lt;i class="lni-tab icons cyan-color contact-info-icon"&gt;
        &lt;/i&gt;
        www.uideck.com
</t>
<t tx="leo.20190426102506.524">       &lt;ul class="social-links"&gt;
    @others
       &lt;/ul&gt;
</t>
<t tx="leo.20190426102506.525">        &lt;li&gt;
    @others
        &lt;/li&gt;
</t>
<t tx="leo.20190426102506.526">         &lt;a class="fa fa-facebook" href="#"&gt;
         &lt;/a&gt;
</t>
<t tx="leo.20190426102506.527">        &lt;li&gt;
    @others
        &lt;/li&gt;
</t>
<t tx="leo.20190426102506.528">         &lt;a class="fa fa-twitter" href="#"&gt;
         &lt;/a&gt;
</t>
<t tx="leo.20190426102506.529">        &lt;li&gt;
    @others
        &lt;/li&gt;
</t>
<t tx="leo.20190426102506.53">        &lt;ol class="carousel-indicators"&gt;
    @others
        &lt;/ol&gt;
</t>
<t tx="leo.20190426102506.530">         &lt;a class="fa fa-instagram" href="#"&gt;
         &lt;/a&gt;
</t>
<t tx="leo.20190426102506.531">        &lt;li&gt;
    @others
        &lt;/li&gt;
</t>
<t tx="leo.20190426102506.532">         &lt;a class="fa fa-linkedin" href="#"&gt;
         &lt;/a&gt;
</t>
<t tx="leo.20190426102506.533">   &lt;div class="container"&gt;
    &lt;!-- Row Starts --&gt;
    @others
   &lt;/div&gt;
   &lt;!-- Container Ends --&gt;
   &lt;!-- Copyright --&gt;
</t>
<t tx="leo.20190426102506.534">    &lt;div class="row section"&gt;
     &lt;!-- Footer Widget Starts --&gt;
    @others
    &lt;/div&gt;
    &lt;!-- Row Ends --&gt;
</t>
<t tx="leo.20190426102506.535">     &lt;div class="footer-widget col-lg-3 col-md-6 col-xs-12 wow fadeIn"&gt;
    @others
     &lt;/div&gt;
     &lt;!-- Footer Widget Ends --&gt;
     &lt;!-- Footer Widget Starts --&gt;
</t>
<t tx="leo.20190426102506.536">      &lt;h3 class="small-title"&gt;
       About Us
      &lt;/h3&gt;
</t>
<t tx="leo.20190426102506.537">      &lt;p&gt;
       Lorem ipsum dolor sit amet, consectetur adipisicing elit. Omnis veritatis eius porro modi hic. Lorem ipsum dolor sit amet, consectetur adipisicing elit.
      &lt;/p&gt;
</t>
<t tx="leo.20190426102506.538">      &lt;div class="social-footer"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.539">       &lt;a href="#"&gt;
    @others
       &lt;/a&gt;
</t>
<t tx="leo.20190426102506.54">         &lt;li class="active" data-slide-to="0" data-target="#carousel-slider"&gt;
         &lt;/li&gt;
</t>
<t tx="leo.20190426102506.540">        &lt;i class="fa fa-facebook icon-round"&gt;
        &lt;/i&gt;
</t>
<t tx="leo.20190426102506.541">       &lt;a href="#"&gt;
    @others
       &lt;/a&gt;
</t>
<t tx="leo.20190426102506.542">        &lt;i class="fa fa-twitter icon-round"&gt;
        &lt;/i&gt;
</t>
<t tx="leo.20190426102506.543">       &lt;a href="#"&gt;
    @others
       &lt;/a&gt;
</t>
<t tx="leo.20190426102506.544">        &lt;i class="fa fa-linkedin icon-round"&gt;
        &lt;/i&gt;
</t>
<t tx="leo.20190426102506.545">       &lt;a href="#"&gt;
    @others
       &lt;/a&gt;
</t>
<t tx="leo.20190426102506.546">        &lt;i class="fa fa-google-plus icon-round"&gt;
        &lt;/i&gt;
</t>
<t tx="leo.20190426102506.547">     &lt;div class="footer-widget col-lg-3 col-md-6 col-xs-12 wow fadeIn" data-wow-delay=".2s"&gt;
    @others
     &lt;/div&gt;
     &lt;!-- Footer Widget Ends --&gt;
     &lt;!-- Footer Widget Starts --&gt;
</t>
<t tx="leo.20190426102506.548">      &lt;h3 class="small-title"&gt;
       Links
      &lt;/h3&gt;
</t>
<t tx="leo.20190426102506.549">      &lt;ul class="menu"&gt;
    @others
      &lt;/ul&gt;
</t>
<t tx="leo.20190426102506.55">         &lt;li data-slide-to="1" data-target="#carousel-slider"&gt;
         &lt;/li&gt;
</t>
<t tx="leo.20190426102506.550">       &lt;li&gt;
    @others
       &lt;/li&gt;
</t>
<t tx="leo.20190426102506.551">        &lt;a href="#"&gt;
         About Us
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.552">       &lt;li&gt;
    @others
       &lt;/li&gt;
</t>
<t tx="leo.20190426102506.553">        &lt;a href="#"&gt;
         Services
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.554">       &lt;li&gt;
    @others
       &lt;/li&gt;
</t>
<t tx="leo.20190426102506.555">        &lt;a href="#"&gt;
         Works
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.556">       &lt;li&gt;
    @others
       &lt;/li&gt;
</t>
<t tx="leo.20190426102506.557">        &lt;a href="#"&gt;
         Pricing
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.558">       &lt;li&gt;
    @others
       &lt;/li&gt;
</t>
<t tx="leo.20190426102506.559">        &lt;a href="#"&gt;
         Contact
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.56">         &lt;li data-slide-to="2" data-target="#carousel-slider"&gt;
         &lt;/li&gt;
</t>
<t tx="leo.20190426102506.560">     &lt;div class="footer-widget col-lg-3 col-md-6 col-xs-12 wow fadeIn" data-wow-delay=".5s"&gt;
    @others
     &lt;/div&gt;
     &lt;!-- Footer Widget Ends --&gt;
     &lt;!-- Footer Widget Starts --&gt;
</t>
<t tx="leo.20190426102506.561">      &lt;h3 class="small-title"&gt;
       GALLERY
      &lt;/h3&gt;
</t>
<t tx="leo.20190426102506.562">      &lt;div class="plain-flicker-gallery"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.563">       &lt;a href="#"&gt;
        &lt;img alt="" src="img/flicker/img1.jpg"/&gt;
       &lt;/a&gt;
</t>
<t tx="leo.20190426102506.564">       &lt;a href="#"&gt;
        &lt;img alt="" src="img/flicker/img2.jpg"/&gt;
       &lt;/a&gt;
</t>
<t tx="leo.20190426102506.565">       &lt;a href="#"&gt;
        &lt;img alt="" src="img/flicker/img3.jpg"/&gt;
       &lt;/a&gt;
</t>
<t tx="leo.20190426102506.566">       &lt;a href="#"&gt;
        &lt;img alt="" src="img/flicker/img4.jpg"/&gt;
       &lt;/a&gt;
</t>
<t tx="leo.20190426102506.567">       &lt;a href="#"&gt;
        &lt;img alt="" src="img/flicker/img5.jpg"/&gt;
       &lt;/a&gt;
</t>
<t tx="leo.20190426102506.568">       &lt;a href="#"&gt;
        &lt;img alt="" src="img/flicker/img6.jpg"/&gt;
       &lt;/a&gt;
</t>
<t tx="leo.20190426102506.569">     &lt;div class="footer-widget col-lg-3 col-md-6 col-xs-12 wow fadeIn" data-wow-delay=".8s"&gt;
    @others
     &lt;/div&gt;
     &lt;!-- Footer Widget Ends --&gt;
</t>
<t tx="leo.20190426102506.57">        &lt;div class="carousel-inner" role="listbox"&gt;
    @others
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.570">      &lt;h3 class="small-title"&gt;
       SUBSCRIBE US
      &lt;/h3&gt;
</t>
<t tx="leo.20190426102506.571">      &lt;div class="contact-us"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.572">       &lt;form&gt;
    @others
       &lt;/form&gt;
</t>
<t tx="leo.20190426102506.573">        &lt;div class="form-group"&gt;
         &lt;input class="form-control" id="exampleInputName2" placeholder="Enter your name" type="text"/&gt;
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.574">        &lt;div class="form-group"&gt;
         &lt;input class="form-control" id="exampleInputEmail2" placeholder="Enter your email" type="email"/&gt;
        &lt;/div&gt;
</t>
<t tx="leo.20190426102506.575">        &lt;button class="btn btn-common" type="submit"&gt;
         Submit
        &lt;/button&gt;
</t>
<t tx="leo.20190426102506.576">   &lt;div id="copyright"&gt;
    @others
   &lt;/div&gt;
   &lt;!-- Copyright  End--&gt;
  &lt;/footer&gt;
  &lt;!-- Footer Section End--&gt;
  &lt;!-- Go to Top Link --&gt;
</t>
<t tx="leo.20190426102506.577">    &lt;div class="container"&gt;
    @others
    &lt;/div&gt;
</t>
<t tx="leo.20190426102506.578">     &lt;div class="row"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.579">      &lt;div class="col-lg-6 col-md-6 col-xs-12"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.58">         &lt;div class="carousel-item active"&gt;
          &lt;img alt="" src="img/slider/bg-1.jpg"/&gt;
    @others
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.580">       &lt;p class="copyright-text"&gt;
        All copyrights reserved © 2018 - Designed &amp;amp; Developed by
    @others
       &lt;/p&gt;
</t>
<t tx="leo.20190426102506.581">        &lt;a href="https://uideck.com" rel="nofollow"&gt;
         UIdeck
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.582">      &lt;div class="col-lg-6 col-md-6 col-xs-12"&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.583">       &lt;ul class="nav nav-inline justify-content-end"&gt;
    @others
       &lt;/ul&gt;
</t>
<t tx="leo.20190426102506.584">        &lt;li class="nav-item"&gt;
    @others
        &lt;/li&gt;
</t>
<t tx="leo.20190426102506.585">         &lt;a class="nav-link active" href="#"&gt;
          Home
         &lt;/a&gt;
</t>
<t tx="leo.20190426102506.586">        &lt;li class="nav-item"&gt;
    @others
        &lt;/li&gt;
</t>
<t tx="leo.20190426102506.587">         &lt;a class="nav-link" href="#"&gt;
          Sitemap
         &lt;/a&gt;
</t>
<t tx="leo.20190426102506.588">        &lt;li class="nav-item"&gt;
    @others
        &lt;/li&gt;
</t>
<t tx="leo.20190426102506.589">         &lt;a class="nav-link" href="#"&gt;
          Privacy Policy
         &lt;/a&gt;
</t>
<t tx="leo.20190426102506.59">          &lt;div class="carousel-caption"&gt;
    @others
          &lt;/div&gt;
</t>
<t tx="leo.20190426102506.590">        &lt;li class="nav-item"&gt;
    @others
        &lt;/li&gt;
</t>
<t tx="leo.20190426102506.591">         &lt;a class="nav-link" href="#"&gt;
          Terms of services
         &lt;/a&gt;
</t>
<t tx="leo.20190426102506.592">  &lt;a class="back-to-top" href="#"&gt;
    @others
  &lt;/a&gt;
  &lt;!-- Preloader --&gt;
</t>
<t tx="leo.20190426102506.593">   &lt;i class="fa fa-arrow-up"&gt;
   &lt;/i&gt;
</t>
<t tx="leo.20190426102506.594">  &lt;div id="preloader"&gt;
    @others
  &lt;/div&gt;
  &lt;!-- End Preloader --&gt;
  &lt;!-- jQuery first, then Popper.js, then Bootstrap JS --&gt;
</t>
<t tx="leo.20190426102506.595">   &lt;div class="loader" id="loader-1"&gt;
   &lt;/div&gt;
</t>
<t tx="leo.20190426102506.6">     &lt;div class="navbar-header"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.60">           &lt;h3 class="slide-title animated fadeInDown"&gt;
    @others
           &lt;/h3&gt;
</t>
<t tx="leo.20190426102506.61">            &lt;span&gt;
             Helium
            &lt;/span&gt;
            - Bootstrap 4 UI Kit
</t>
<t tx="leo.20190426102506.62">           &lt;h5 class="slide-text animated fadeIn"&gt;
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit
            &lt;br/&gt;
            Curabitur ultricies nisi Nam eget dui. Etiam rhoncus
           &lt;/h5&gt;
</t>
<t tx="leo.20190426102506.63">           &lt;a class="btn btn-lg btn-common animated fadeInUp" href="#"&gt;
            Get Started
           &lt;/a&gt;
</t>
<t tx="leo.20190426102506.64">           &lt;a class="btn btn-lg btn-border animated fadeInUp" href="#"&gt;
            Learn More
           &lt;/a&gt;
</t>
<t tx="leo.20190426102506.65">         &lt;div class="carousel-item"&gt;
          &lt;img alt="" src="img/slider/bg-2.jpg"/&gt;
    @others
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.66">          &lt;div class="carousel-caption"&gt;
    @others
          &lt;/div&gt;
</t>
<t tx="leo.20190426102506.67">           &lt;h3 class="slide-title animated fadeInDown"&gt;
    @others
           &lt;/h3&gt;
</t>
<t tx="leo.20190426102506.68">            &lt;span&gt;
             Cutting-edge
            &lt;/span&gt;
            Features
</t>
<t tx="leo.20190426102506.69">           &lt;h5 class="slide-text animated fadeIn"&gt;
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit
            &lt;br/&gt;
            Curabitur ultricies nisi Nam eget dui. Etiam rhoncus
           &lt;/h5&gt;
</t>
<t tx="leo.20190426102506.7">      &lt;button aria-controls="main-navbar" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler" data-target="#main-navbar" data-toggle="collapse" type="button"&gt;
    @others
      &lt;/button&gt;
</t>
<t tx="leo.20190426102506.70">           &lt;a class="btn btn-lg btn-common animated fadeInUp" href="#"&gt;
            Download Now
           &lt;/a&gt;
</t>
<t tx="leo.20190426102506.71">         &lt;div class="carousel-item"&gt;
          &lt;img alt="" src="img/slider/bg-3.jpg"/&gt;
    @others
         &lt;/div&gt;
</t>
<t tx="leo.20190426102506.72">          &lt;div class="carousel-caption"&gt;
    @others
          &lt;/div&gt;
</t>
<t tx="leo.20190426102506.73">           &lt;h3 class="slide-title animated fadeInDown"&gt;
    @others
           &lt;/h3&gt;
</t>
<t tx="leo.20190426102506.74">            &lt;span&gt;
             100+
            &lt;/span&gt;
            UI Blocks &amp;amp; Components
</t>
<t tx="leo.20190426102506.75">           &lt;h5 class="slide-text animated fadeIn"&gt;
            Lorem ipsum dolor sit amet, consectetuer adipiscing elit
            &lt;br/&gt;
            Curabitur ultricies nisi Nam eget dui. Etiam rhoncus
           &lt;/h5&gt;
</t>
<t tx="leo.20190426102506.76">           &lt;a class="btn btn-lg btn-border animated fadeInUp" href="#"&gt;
            Get Started
           &lt;/a&gt;
</t>
<t tx="leo.20190426102506.77">           &lt;a class="btn btn-lg btn-common animated fadeInUp" href="#"&gt;
            Download
           &lt;/a&gt;
</t>
<t tx="leo.20190426102506.78">        &lt;a class="carousel-control-prev" data-slide="prev" href="#carousel-slider" role="button"&gt;
    @others
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.79">         &lt;i class="fa fa-chevron-left"&gt;
         &lt;/i&gt;
</t>
<t tx="leo.20190426102506.8">       &lt;span class="navbar-toggler-icon"&gt;
       &lt;/span&gt;
</t>
<t tx="leo.20190426102506.80">        &lt;a class="carousel-control-next" data-slide="next" href="#carousel-slider" role="button"&gt;
    @others
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.81">         &lt;i class="fa fa-chevron-right"&gt;
         &lt;/i&gt;
</t>
<t tx="leo.20190426102506.82">  &lt;div class="section-padding" id="about"&gt;
    @others
  &lt;/div&gt;
  &lt;!-- About Section End --&gt;
  &lt;!-- Services Section Start --&gt;
  &lt;section class="section-padding" id="services"&gt;
</t>
<t tx="leo.20190426102506.83">   &lt;div class="container"&gt;
    @others
   &lt;/div&gt;
</t>
<t tx="leo.20190426102506.84">    &lt;div class="row"&gt;
    @others
    &lt;/div&gt;
</t>
<t tx="leo.20190426102506.85">     &lt;div class="col-lg-3 col-md-6 col-xs-12"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.86">      &lt;div class="about block text-center"&gt;
       &lt;img alt="" src="img/about/img1.png"/&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.87">       &lt;h5&gt;
    @others
       &lt;/h5&gt;
</t>
<t tx="leo.20190426102506.88">        &lt;a href="#"&gt;
         About Title
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.89">       &lt;p&gt;
        Quisque sit amet libero purus. Nulla a dignissim quam. In hac habitasse platea dictumst.
       &lt;/p&gt;
</t>
<t tx="leo.20190426102506.9">       &lt;span class="icon-menu"&gt;
       &lt;/span&gt;
</t>
<t tx="leo.20190426102506.90">     &lt;div class="col-lg-3 col-md-6 col-xs-12"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.91">      &lt;div class="about block text-center"&gt;
       &lt;img alt="" src="img/about/img2.png"/&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.92">       &lt;h5&gt;
    @others
       &lt;/h5&gt;
</t>
<t tx="leo.20190426102506.93">        &lt;a href="#"&gt;
         About Title
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.94">       &lt;p&gt;
        Quisque sit amet libero purus. Nulla a dignissim quam. In hac habitasse platea dictumst.
       &lt;/p&gt;
</t>
<t tx="leo.20190426102506.95">     &lt;div class="col-lg-3 col-md-6 col-xs-12"&gt;
    @others
     &lt;/div&gt;
</t>
<t tx="leo.20190426102506.96">      &lt;div class="about block text-center"&gt;
       &lt;img alt="" src="img/about/img3.png"/&gt;
    @others
      &lt;/div&gt;
</t>
<t tx="leo.20190426102506.97">       &lt;h5&gt;
    @others
       &lt;/h5&gt;
</t>
<t tx="leo.20190426102506.98">        &lt;a href="#"&gt;
         About Title
        &lt;/a&gt;
</t>
<t tx="leo.20190426102506.99">       &lt;p&gt;
        Quisque sit amet libero purus. Nulla a dignissim quam. In hac habitasse platea dictumst.
       &lt;/p&gt;
</t>
<t tx="leo.20190426102601.1">&lt;!-- jQuery first, then Popper.js, then Bootstrap JS --&gt;
&lt;script src="js/jquery-min.js"&gt;&lt;/script&gt;
&lt;script src="js/popper.min.js"&gt;&lt;/script&gt;
&lt;script src="js/bootstrap.min.js"&gt;&lt;/script&gt;
&lt;script src="js/owl.carousel.min.js"&gt;&lt;/script&gt;
&lt;script src="js/jquery.mixitup.js"&gt;&lt;/script&gt;
&lt;script src="js/jquery.countTo.js"&gt;&lt;/script&gt;
&lt;script src="js/jquery.nav.js"&gt;&lt;/script&gt;
&lt;script src="js/scrolling-nav.js"&gt;&lt;/script&gt;
&lt;script src="js/jquery.easing.min.js"&gt;&lt;/script&gt;
&lt;script src="js/jquery.slicknav.js"&gt;&lt;/script&gt;
&lt;script src="js/form-validator.min.js"&gt;&lt;/script&gt;
&lt;script src="js/contact-form-script.js"&gt;&lt;/script&gt;
&lt;script src="js/main.js"&gt;&lt;/script&gt;</t>
</tnodes>
</leo_file>
